<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItemNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItem::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItem::class;
    }
    /**
     * @return \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItem|Reference
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItem|Reference
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItem();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (\array_key_exists('acceptListID', $data)) {
            $object->setAcceptListID(TypeValidator::assertInt($data['acceptListID'], 'acceptListID'));
            unset($data['acceptListID']);
        }
        if (\array_key_exists('addedToAcceptList', $data)) {
            $object->setAddedToAcceptList(TypeValidator::assertBool($data['addedToAcceptList'], 'addedToAcceptList'));
            unset($data['addedToAcceptList']);
        }
        if (\array_key_exists('addressName', $data)) {
            $object->setAddressName(TypeValidator::assertBool($data['addressName'], 'addressName'));
            unset($data['addressName']);
        }
        if (\array_key_exists('autoFalsePositive', $data)) {
            $object->setAutoFalsePositive(TypeValidator::assertBool($data['autoFalsePositive'], 'autoFalsePositive'));
            unset($data['autoFalsePositive']);
        }
        if (\array_key_exists('bestAddressIsPartial', $data)) {
            $object->setBestAddressIsPartial(TypeValidator::assertBool($data['bestAddressIsPartial'], 'bestAddressIsPartial'));
            unset($data['bestAddressIsPartial']);
        }
        if (\array_key_exists('bestCountryScore', $data)) {
            $object->setBestCountryScore(TypeValidator::assertInt($data['bestCountryScore'], 'bestCountryScore'));
            unset($data['bestCountryScore']);
        }
        if (\array_key_exists('bestCountryType', $data)) {
            $object->setBestCountryType(TypeValidator::assertString($data['bestCountryType'], 'bestCountryType'));
            unset($data['bestCountryType']);
        }
        if (\array_key_exists('bestDOBIsPartial', $data)) {
            $object->setBestDOBIsPartial(TypeValidator::assertBool($data['bestDOBIsPartial'], 'bestDOBIsPartial'));
            unset($data['bestDOBIsPartial']);
        }
        if (\array_key_exists('bestName', $data)) {
            $object->setBestName(TypeValidator::assertString($data['bestName'], 'bestName'));
            unset($data['bestName']);
        }
        if (\array_key_exists('bestNameScore', $data)) {
            $object->setBestNameScore(TypeValidator::assertInt($data['bestNameScore'], 'bestNameScore'));
            unset($data['bestNameScore']);
        }
        if (\array_key_exists('checkSum', $data)) {
            $object->setCheckSum(TypeValidator::assertInt($data['checkSum'], 'checkSum'));
            unset($data['checkSum']);
        }
        if (\array_key_exists('conflicts', $data)) {
            $value = $this->denormalizer->denormalize($data['conflicts'], \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItemConflicts::class, 'json', $context);
            if (!$value instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItemConflicts) {
                throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItemConflicts, got ' . get_debug_type($value));
            }
            $object->setConflicts($value);
            unset($data['conflicts']);
        }
        if (\array_key_exists('entityDetails', $data)) {
            $value_1 = $this->denormalizer->denormalize($data['entityDetails'], \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItemEntityDetails::class, 'json', $context);
            if (!$value_1 instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItemEntityDetails) {
                throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItemEntityDetails, got ' . get_debug_type($value_1));
            }
            $object->setEntityDetails($value_1);
            unset($data['entityDetails']);
        }
        if (\array_key_exists('entityName', $data)) {
            $object->setEntityName(TypeValidator::assertString($data['entityName'], 'entityName'));
            unset($data['entityName']);
        }
        if (\array_key_exists('entityScore', $data)) {
            $object->setEntityScore(TypeValidator::assertInt($data['entityScore'], 'entityScore'));
            unset($data['entityScore']);
        }
        if (\array_key_exists('entityUniqueID', $data)) {
            $object->setEntityUniqueID(TypeValidator::assertString($data['entityUniqueID'], 'entityUniqueID'));
            unset($data['entityUniqueID']);
        }
        if (\array_key_exists('falsePositive', $data)) {
            $object->setFalsePositive(TypeValidator::assertBool($data['falsePositive'], 'falsePositive'));
            unset($data['falsePositive']);
        }
        if (\array_key_exists('file', $data)) {
            $value_2 = $this->denormalizer->denormalize($data['file'], \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItemFile::class, 'json', $context);
            if (!$value_2 instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItemFile) {
                throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItemFile, got ' . get_debug_type($value_2));
            }
            $object->setFile($value_2);
            unset($data['file']);
        }
        if (\array_key_exists('gatewayOFACScreeningIndicatorMatch', $data)) {
            $object->setGatewayOFACScreeningIndicatorMatch(TypeValidator::assertBool($data['gatewayOFACScreeningIndicatorMatch'], 'gatewayOFACScreeningIndicatorMatch'));
            unset($data['gatewayOFACScreeningIndicatorMatch']);
        }
        if (\array_key_exists('id', $data)) {
            $object->setId(TypeValidator::assertInt($data['id'], 'id'));
            unset($data['id']);
        }
        if (\array_key_exists('matchReAlert', $data)) {
            $object->setMatchReAlert(TypeValidator::assertBool($data['matchReAlert'], 'matchReAlert'));
            unset($data['matchReAlert']);
        }
        if (\array_key_exists('previousResultID', $data)) {
            $object->setPreviousResultID(TypeValidator::assertInt($data['previousResultID'], 'previousResultID'));
            unset($data['previousResultID']);
        }
        if (\array_key_exists('reasonListed', $data)) {
            $object->setReasonListed(TypeValidator::assertString($data['reasonListed'], 'reasonListed'));
            unset($data['reasonListed']);
        }
        if (\array_key_exists('resultDate', $data)) {
            $object->setResultDate(TypeValidator::assertString($data['resultDate'], 'resultDate'));
            unset($data['resultDate']);
        }
        if (\array_key_exists('secondaryOFACScreeningIndicatorMatch', $data)) {
            $object->setSecondaryOFACScreeningIndicatorMatch(TypeValidator::assertBool($data['secondaryOFACScreeningIndicatorMatch'], 'secondaryOFACScreeningIndicatorMatch'));
            unset($data['secondaryOFACScreeningIndicatorMatch']);
        }
        if (\array_key_exists('trueMatch', $data)) {
            $object->setTrueMatch(TypeValidator::assertBool($data['trueMatch'], 'trueMatch'));
            unset($data['trueMatch']);
        }
        foreach ($data as $key => $value_3) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $object[$key] = $value_3;
            }
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItem) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItem, got ' . get_debug_type($data));
        }
        $dataArray = [];
        if ($data->isInitialized('acceptListID')) {
            $dataArray['acceptListID'] = $data->getAcceptListID();
        }
        if ($data->isInitialized('addedToAcceptList')) {
            $dataArray['addedToAcceptList'] = $data->getAddedToAcceptList();
        }
        if ($data->isInitialized('addressName')) {
            $dataArray['addressName'] = $data->getAddressName();
        }
        if ($data->isInitialized('autoFalsePositive')) {
            $dataArray['autoFalsePositive'] = $data->getAutoFalsePositive();
        }
        if ($data->isInitialized('bestAddressIsPartial')) {
            $dataArray['bestAddressIsPartial'] = $data->getBestAddressIsPartial();
        }
        if ($data->isInitialized('bestCountryScore')) {
            $dataArray['bestCountryScore'] = $data->getBestCountryScore();
        }
        if ($data->isInitialized('bestCountryType')) {
            $dataArray['bestCountryType'] = $data->getBestCountryType();
        }
        if ($data->isInitialized('bestDOBIsPartial')) {
            $dataArray['bestDOBIsPartial'] = $data->getBestDOBIsPartial();
        }
        if ($data->isInitialized('bestName')) {
            $dataArray['bestName'] = $data->getBestName();
        }
        if ($data->isInitialized('bestNameScore')) {
            $dataArray['bestNameScore'] = $data->getBestNameScore();
        }
        if ($data->isInitialized('checkSum')) {
            $dataArray['checkSum'] = $data->getCheckSum();
        }
        if ($data->isInitialized('conflicts')) {
            $dataArray['conflicts'] = $this->normalizer->normalize($data->getConflicts(), 'json', $context);
        }
        if ($data->isInitialized('entityDetails')) {
            $dataArray['entityDetails'] = $this->normalizer->normalize($data->getEntityDetails(), 'json', $context);
        }
        if ($data->isInitialized('entityName')) {
            $dataArray['entityName'] = $data->getEntityName();
        }
        if ($data->isInitialized('entityScore')) {
            $dataArray['entityScore'] = $data->getEntityScore();
        }
        if ($data->isInitialized('entityUniqueID')) {
            $dataArray['entityUniqueID'] = $data->getEntityUniqueID();
        }
        if ($data->isInitialized('falsePositive')) {
            $dataArray['falsePositive'] = $data->getFalsePositive();
        }
        if ($data->isInitialized('file')) {
            $dataArray['file'] = $this->normalizer->normalize($data->getFile(), 'json', $context);
        }
        if ($data->isInitialized('gatewayOFACScreeningIndicatorMatch')) {
            $dataArray['gatewayOFACScreeningIndicatorMatch'] = $data->getGatewayOFACScreeningIndicatorMatch();
        }
        if ($data->isInitialized('id')) {
            $dataArray['id'] = $data->getId();
        }
        if ($data->isInitialized('matchReAlert')) {
            $dataArray['matchReAlert'] = $data->getMatchReAlert();
        }
        if ($data->isInitialized('previousResultID')) {
            $dataArray['previousResultID'] = $data->getPreviousResultID();
        }
        if ($data->isInitialized('reasonListed')) {
            $dataArray['reasonListed'] = $data->getReasonListed();
        }
        if ($data->isInitialized('resultDate')) {
            $dataArray['resultDate'] = $data->getResultDate();
        }
        if ($data->isInitialized('secondaryOFACScreeningIndicatorMatch')) {
            $dataArray['secondaryOFACScreeningIndicatorMatch'] = $data->getSecondaryOFACScreeningIndicatorMatch();
        }
        if ($data->isInitialized('trueMatch')) {
            $dataArray['trueMatch'] = $data->getTrueMatch();
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $dataArray[(string) $key] = $value;
            }
        }
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model\ComplianceSearchResultDataBodySearchResultRecordsItemWatchlistMatchesItem::class => false];
    }
}