<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class NamespaceInfoNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model\NamespaceInfo::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && $data::class === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model\NamespaceInfo::class;
    }
    /**
     * The denormalized result is either a \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model\NamespaceInfo or a Reference.
     * Native return type is `mixed` for Symfony interface covariance — callers
     * must narrow via TypeValidator::assertInstanceOf.
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model\NamespaceInfo();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (\array_key_exists('api_host', $data)) {
            $object->setApiHost(TypeValidator::assertString($data['api_host'], 'api_host'));
            unset($data['api_host']);
        }
        if (\array_key_exists('namespace', $data)) {
            $object->setNamespace(TypeValidator::assertString($data['namespace'], 'namespace'));
            unset($data['namespace']);
        }
        if (\array_key_exists('created_at', $data)) {
            $object->setCreatedAt(TypeValidator::assertString($data['created_at'], 'created_at'));
            unset($data['created_at']);
        }
        if (\array_key_exists('updated_at', $data)) {
            $object->setUpdatedAt(TypeValidator::assertString($data['updated_at'], 'updated_at'));
            unset($data['updated_at']);
        }
        if (\array_key_exists('label', $data)) {
            $object->setLabel(TypeValidator::assertString($data['label'], 'label'));
            unset($data['label']);
        }
        if (\array_key_exists('region', $data)) {
            $object->setRegion(TypeValidator::assertString($data['region'], 'region'));
            unset($data['region']);
        }
        if (\array_key_exists('uuid', $data)) {
            $object->setUuid(TypeValidator::assertString($data['uuid'], 'uuid'));
            unset($data['uuid']);
        }
        if (\array_key_exists('key', $data)) {
            $object->setKey(TypeValidator::assertString($data['key'], 'key'));
            unset($data['key']);
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $object[$key] = $value;
            }
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model\NamespaceInfo) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model\NamespaceInfo, got ' . get_debug_type($data));
        }
        $dataArray = [];
        if ($data->isInitialized('apiHost')) {
            $dataArray['api_host'] = $data->getApiHost();
        }
        if ($data->isInitialized('namespace')) {
            $dataArray['namespace'] = $data->getNamespace();
        }
        if ($data->isInitialized('createdAt')) {
            $dataArray['created_at'] = $data->getCreatedAt();
        }
        if ($data->isInitialized('updatedAt')) {
            $dataArray['updated_at'] = $data->getUpdatedAt();
        }
        if ($data->isInitialized('label')) {
            $dataArray['label'] = $data->getLabel();
        }
        if ($data->isInitialized('region')) {
            $dataArray['region'] = $data->getRegion();
        }
        if ($data->isInitialized('uuid')) {
            $dataArray['uuid'] = $data->getUuid();
        }
        if ($data->isInitialized('key')) {
            $dataArray['key'] = $data->getKey();
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', strval($key)) === 1) {
                $dataArray[$key] = $value;
            }
        }
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model\NamespaceInfo::class => false];
    }
}