<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ApiEvaluationRun extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Whether agent is deleted
     */
    protected bool $agentDeleted;
    /**
     * The agent deployment name
     */
    protected string $agentDeploymentName;
    /**
     * Agent name
     */
    protected string $agentName;
    /**
     * Agent UUID.
     */
    protected string $agentUuid;
    /**
     * Version hash
     */
    protected string $agentVersionHash;
    /**
     * Agent workspace uuid
     */
    protected string $agentWorkspaceUuid;
    protected string $createdByUserEmail;
    protected string $createdByUserId;
    /**
     * The error description
     */
    protected string $errorDescription;
    /**
     * Evaluation run UUID.
     */
    protected string $evaluationRunUuid;
    /**
     * Evaluation test case workspace uuid
     */
    protected string $evaluationTestCaseWorkspaceUuid;
    /**
     * Run end time.
     */
    protected \DateTime $finishedAt;
    /**
     * The pass status of the evaluation run based on the star metric.
     */
    protected bool $passStatus;
    /**
     * Run queued time.
     */
    protected \DateTime $queuedAt;
    /**
     * @var list<ApiEvaluationMetricResult>
     */
    protected array $runLevelMetricResults;
    /**
     * Run name.
     */
    protected string $runName;
    protected ApiEvaluationMetricResult $starMetricResult;
    /**
     * Run start time.
     */
    protected \DateTime $startedAt;
    /**
     * Evaluation Run Statuses
     */
    protected string $status = 'EVALUATION_RUN_STATUS_UNSPECIFIED';
    /**
     * Test case description.
     */
    protected string $testCaseDescription;
    /**
     * Test case name.
     */
    protected string $testCaseName;
    /**
     * Test-case UUID.
     */
    protected string $testCaseUuid;
    /**
     * Test-case-version.
     */
    protected int $testCaseVersion;
    /**
     * Whether agent is deleted
     */
    public function getAgentDeleted(): bool
    {
        return $this->agentDeleted;
    }
    /**
     * Whether agent is deleted
     */
    public function setAgentDeleted(bool $agentDeleted): self
    {
        $this->initialized['agentDeleted'] = true;
        $this->agentDeleted = $agentDeleted;
        return $this;
    }
    /**
     * The agent deployment name
     */
    public function getAgentDeploymentName(): string
    {
        return $this->agentDeploymentName;
    }
    /**
     * The agent deployment name
     */
    public function setAgentDeploymentName(string $agentDeploymentName): self
    {
        $this->initialized['agentDeploymentName'] = true;
        $this->agentDeploymentName = $agentDeploymentName;
        return $this;
    }
    /**
     * Agent name
     */
    public function getAgentName(): string
    {
        return $this->agentName;
    }
    /**
     * Agent name
     */
    public function setAgentName(string $agentName): self
    {
        $this->initialized['agentName'] = true;
        $this->agentName = $agentName;
        return $this;
    }
    /**
     * Agent UUID.
     */
    public function getAgentUuid(): string
    {
        return $this->agentUuid;
    }
    /**
     * Agent UUID.
     */
    public function setAgentUuid(string $agentUuid): self
    {
        $this->initialized['agentUuid'] = true;
        $this->agentUuid = $agentUuid;
        return $this;
    }
    /**
     * Version hash
     */
    public function getAgentVersionHash(): string
    {
        return $this->agentVersionHash;
    }
    /**
     * Version hash
     */
    public function setAgentVersionHash(string $agentVersionHash): self
    {
        $this->initialized['agentVersionHash'] = true;
        $this->agentVersionHash = $agentVersionHash;
        return $this;
    }
    /**
     * Agent workspace uuid
     */
    public function getAgentWorkspaceUuid(): string
    {
        return $this->agentWorkspaceUuid;
    }
    /**
     * Agent workspace uuid
     */
    public function setAgentWorkspaceUuid(string $agentWorkspaceUuid): self
    {
        $this->initialized['agentWorkspaceUuid'] = true;
        $this->agentWorkspaceUuid = $agentWorkspaceUuid;
        return $this;
    }
    public function getCreatedByUserEmail(): string
    {
        return $this->createdByUserEmail;
    }
    public function setCreatedByUserEmail(string $createdByUserEmail): self
    {
        $this->initialized['createdByUserEmail'] = true;
        $this->createdByUserEmail = $createdByUserEmail;
        return $this;
    }
    public function getCreatedByUserId(): string
    {
        return $this->createdByUserId;
    }
    public function setCreatedByUserId(string $createdByUserId): self
    {
        $this->initialized['createdByUserId'] = true;
        $this->createdByUserId = $createdByUserId;
        return $this;
    }
    /**
     * The error description
     */
    public function getErrorDescription(): string
    {
        return $this->errorDescription;
    }
    /**
     * The error description
     */
    public function setErrorDescription(string $errorDescription): self
    {
        $this->initialized['errorDescription'] = true;
        $this->errorDescription = $errorDescription;
        return $this;
    }
    /**
     * Evaluation run UUID.
     */
    public function getEvaluationRunUuid(): string
    {
        return $this->evaluationRunUuid;
    }
    /**
     * Evaluation run UUID.
     */
    public function setEvaluationRunUuid(string $evaluationRunUuid): self
    {
        $this->initialized['evaluationRunUuid'] = true;
        $this->evaluationRunUuid = $evaluationRunUuid;
        return $this;
    }
    /**
     * Evaluation test case workspace uuid
     */
    public function getEvaluationTestCaseWorkspaceUuid(): string
    {
        return $this->evaluationTestCaseWorkspaceUuid;
    }
    /**
     * Evaluation test case workspace uuid
     */
    public function setEvaluationTestCaseWorkspaceUuid(string $evaluationTestCaseWorkspaceUuid): self
    {
        $this->initialized['evaluationTestCaseWorkspaceUuid'] = true;
        $this->evaluationTestCaseWorkspaceUuid = $evaluationTestCaseWorkspaceUuid;
        return $this;
    }
    /**
     * Run end time.
     */
    public function getFinishedAt(): \DateTime
    {
        return $this->finishedAt;
    }
    /**
     * Run end time.
     */
    public function setFinishedAt(\DateTime $finishedAt): self
    {
        $this->initialized['finishedAt'] = true;
        $this->finishedAt = $finishedAt;
        return $this;
    }
    /**
     * The pass status of the evaluation run based on the star metric.
     */
    public function getPassStatus(): bool
    {
        return $this->passStatus;
    }
    /**
     * The pass status of the evaluation run based on the star metric.
     */
    public function setPassStatus(bool $passStatus): self
    {
        $this->initialized['passStatus'] = true;
        $this->passStatus = $passStatus;
        return $this;
    }
    /**
     * Run queued time.
     */
    public function getQueuedAt(): \DateTime
    {
        return $this->queuedAt;
    }
    /**
     * Run queued time.
     */
    public function setQueuedAt(\DateTime $queuedAt): self
    {
        $this->initialized['queuedAt'] = true;
        $this->queuedAt = $queuedAt;
        return $this;
    }
    /**
     * @return list<ApiEvaluationMetricResult>
     */
    public function getRunLevelMetricResults(): array
    {
        return $this->runLevelMetricResults;
    }
    /**
     * @param list<ApiEvaluationMetricResult> $runLevelMetricResults
     */
    public function setRunLevelMetricResults(array $runLevelMetricResults): self
    {
        $this->initialized['runLevelMetricResults'] = true;
        $this->runLevelMetricResults = $runLevelMetricResults;
        return $this;
    }
    /**
     * Run name.
     */
    public function getRunName(): string
    {
        return $this->runName;
    }
    /**
     * Run name.
     */
    public function setRunName(string $runName): self
    {
        $this->initialized['runName'] = true;
        $this->runName = $runName;
        return $this;
    }
    public function getStarMetricResult(): ApiEvaluationMetricResult
    {
        return $this->starMetricResult;
    }
    public function setStarMetricResult(ApiEvaluationMetricResult $starMetricResult): self
    {
        $this->initialized['starMetricResult'] = true;
        $this->starMetricResult = $starMetricResult;
        return $this;
    }
    /**
     * Run start time.
     */
    public function getStartedAt(): \DateTime
    {
        return $this->startedAt;
    }
    /**
     * Run start time.
     */
    public function setStartedAt(\DateTime $startedAt): self
    {
        $this->initialized['startedAt'] = true;
        $this->startedAt = $startedAt;
        return $this;
    }
    /**
     * Evaluation Run Statuses
     */
    public function getStatus(): string
    {
        return $this->status;
    }
    /**
     * Evaluation Run Statuses
     */
    public function setStatus(string $status): self
    {
        $this->initialized['status'] = true;
        $this->status = $status;
        return $this;
    }
    /**
     * Test case description.
     */
    public function getTestCaseDescription(): string
    {
        return $this->testCaseDescription;
    }
    /**
     * Test case description.
     */
    public function setTestCaseDescription(string $testCaseDescription): self
    {
        $this->initialized['testCaseDescription'] = true;
        $this->testCaseDescription = $testCaseDescription;
        return $this;
    }
    /**
     * Test case name.
     */
    public function getTestCaseName(): string
    {
        return $this->testCaseName;
    }
    /**
     * Test case name.
     */
    public function setTestCaseName(string $testCaseName): self
    {
        $this->initialized['testCaseName'] = true;
        $this->testCaseName = $testCaseName;
        return $this;
    }
    /**
     * Test-case UUID.
     */
    public function getTestCaseUuid(): string
    {
        return $this->testCaseUuid;
    }
    /**
     * Test-case UUID.
     */
    public function setTestCaseUuid(string $testCaseUuid): self
    {
        $this->initialized['testCaseUuid'] = true;
        $this->testCaseUuid = $testCaseUuid;
        return $this;
    }
    /**
     * Test-case-version.
     */
    public function getTestCaseVersion(): int
    {
        return $this->testCaseVersion;
    }
    /**
     * Test-case-version.
     */
    public function setTestCaseVersion(int $testCaseVersion): self
    {
        $this->initialized['testCaseVersion'] = true;
        $this->testCaseVersion = $testCaseVersion;
        return $this;
    }
}