<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ApiFileUploadDataSource extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The original file name
     */
    protected string $originalFileName;
    /**
     * The size of the file in bytes
     */
    protected string $sizeInBytes;
    /**
     * The object key the file was stored as
     */
    protected string $storedObjectKey;
    /**
     * The original file name
     */
    public function getOriginalFileName(): string
    {
        return $this->originalFileName;
    }
    /**
     * The original file name
     *
     * @return self
     */
    public function setOriginalFileName(string $originalFileName): self
    {
        $this->initialized['originalFileName'] = true;
        $this->originalFileName = $originalFileName;
        return $this;
    }
    /**
     * The size of the file in bytes
     */
    public function getSizeInBytes(): string
    {
        return $this->sizeInBytes;
    }
    /**
     * The size of the file in bytes
     *
     * @return self
     */
    public function setSizeInBytes(string $sizeInBytes): self
    {
        $this->initialized['sizeInBytes'] = true;
        $this->sizeInBytes = $sizeInBytes;
        return $this;
    }
    /**
     * The object key the file was stored as
     */
    public function getStoredObjectKey(): string
    {
        return $this->storedObjectKey;
    }
    /**
     * The object key the file was stored as
     *
     * @return self
     */
    public function setStoredObjectKey(string $storedObjectKey): self
    {
        $this->initialized['storedObjectKey'] = true;
        $this->storedObjectKey = $storedObjectKey;
        return $this;
    }
}