<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class AppsGetInstanceSizeResponse extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected mixed $instanceSize = null;
    public function getInstanceSize(): mixed
    {
        return $this->instanceSize;
    }
    public function setInstanceSize(mixed $instanceSize): self
    {
        $this->initialized['instanceSize'] = true;
        $this->instanceSize = $instanceSize;
        return $this;
    }
}