<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class AppsCreateDeploymentRequest extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected bool $forceBuild;
    public function getForceBuild(): bool
    {
        return $this->forceBuild;
    }
    public function setForceBuild(bool $forceBuild): self
    {
        $this->initialized['forceBuild'] = true;
        $this->forceBuild = $forceBuild;
        return $this;
    }
}