<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ElasticsearchLogsink extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Elasticsearch connection URL
     */
    protected string $url;
    /**
     * Elasticsearch index prefix
     */
    protected string $indexPrefix;
    /**
     * Maximum number of days of logs to keep
     */
    protected int $indexDaysMax = 7;
    /**
     * Elasticsearch request timeout limit
     */
    protected float $timeout = 10;
    /**
     * PEM encoded CA certificate
     */
    protected string $ca;
    /**
     * Elasticsearch connection URL
     */
    public function getUrl(): string
    {
        return $this->url;
    }
    /**
     * Elasticsearch connection URL
     *
     * @return self
     */
    public function setUrl(string $url): self
    {
        $this->initialized['url'] = true;
        $this->url = $url;
        return $this;
    }
    /**
     * Elasticsearch index prefix
     */
    public function getIndexPrefix(): string
    {
        return $this->indexPrefix;
    }
    /**
     * Elasticsearch index prefix
     *
     * @return self
     */
    public function setIndexPrefix(string $indexPrefix): self
    {
        $this->initialized['indexPrefix'] = true;
        $this->indexPrefix = $indexPrefix;
        return $this;
    }
    /**
     * Maximum number of days of logs to keep
     */
    public function getIndexDaysMax(): int
    {
        return $this->indexDaysMax;
    }
    /**
     * Maximum number of days of logs to keep
     *
     * @return self
     */
    public function setIndexDaysMax(int $indexDaysMax): self
    {
        $this->initialized['indexDaysMax'] = true;
        $this->indexDaysMax = $indexDaysMax;
        return $this;
    }
    /**
     * Elasticsearch request timeout limit
     */
    public function getTimeout(): float
    {
        return $this->timeout;
    }
    /**
     * Elasticsearch request timeout limit
     *
     * @return self
     */
    public function setTimeout(float $timeout): self
    {
        $this->initialized['timeout'] = true;
        $this->timeout = $timeout;
        return $this;
    }
    /**
     * PEM encoded CA certificate
     */
    public function getCa(): string
    {
        return $this->ca;
    }
    /**
     * PEM encoded CA certificate
     *
     * @return self
     */
    public function setCa(string $ca): self
    {
        $this->initialized['ca'] = true;
        $this->ca = $ca;
        return $this;
    }
}