<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class RegistryCreate extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * A globally unique name for the container registry. Must be lowercase and be composed only of numbers, letters and `-`, up to a limit of 63 characters.
     */
    protected string $name;
    /**
     * The slug of the subscription tier to sign up for. Valid values can be retrieved using the options endpoint.
     */
    protected string $subscriptionTierSlug;
    /**
     * Slug of the region where registry data is stored. When not provided, a region will be selected.
     */
    protected string $region;
    /**
     * A globally unique name for the container registry. Must be lowercase and be composed only of numbers, letters and `-`, up to a limit of 63 characters.
     */
    public function getName(): string
    {
        return $this->name;
    }
    /**
     * A globally unique name for the container registry. Must be lowercase and be composed only of numbers, letters and `-`, up to a limit of 63 characters.
     *
     * @return self
     */
    public function setName(string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;
        return $this;
    }
    /**
     * The slug of the subscription tier to sign up for. Valid values can be retrieved using the options endpoint.
     */
    public function getSubscriptionTierSlug(): string
    {
        return $this->subscriptionTierSlug;
    }
    /**
     * The slug of the subscription tier to sign up for. Valid values can be retrieved using the options endpoint.
     *
     * @return self
     */
    public function setSubscriptionTierSlug(string $subscriptionTierSlug): self
    {
        $this->initialized['subscriptionTierSlug'] = true;
        $this->subscriptionTierSlug = $subscriptionTierSlug;
        return $this;
    }
    /**
     * Slug of the region where registry data is stored. When not provided, a region will be selected.
     */
    public function getRegion(): string
    {
        return $this->region;
    }
    /**
     * Slug of the region where registry data is stored. When not provided, a region will be selected.
     *
     * @return self
     */
    public function setRegion(string $region): self
    {
        $this->initialized['region'] = true;
        $this->region = $region;
        return $this;
    }
}