<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class RegionState extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $status;
    protected string $statusChangedAt;
    protected float $thirtyDayUptimePercentage;
    public function getStatus(): string
    {
        return $this->status;
    }
    public function setStatus(string $status): self
    {
        $this->initialized['status'] = true;
        $this->status = $status;
        return $this;
    }
    public function getStatusChangedAt(): string
    {
        return $this->statusChangedAt;
    }
    public function setStatusChangedAt(string $statusChangedAt): self
    {
        $this->initialized['statusChangedAt'] = true;
        $this->statusChangedAt = $statusChangedAt;
        return $this;
    }
    public function getThirtyDayUptimePercentage(): float
    {
        return $this->thirtyDayUptimePercentage;
    }
    public function setThirtyDayUptimePercentage(float $thirtyDayUptimePercentage): self
    {
        $this->initialized['thirtyDayUptimePercentage'] = true;
        $this->thirtyDayUptimePercentage = $thirtyDayUptimePercentage;
        return $this;
    }
}