<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ResponseAppsValidateRollback extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Indicates whether the app can be rolled back to the specified deployment.
     *
     */
    protected bool $valid;
    protected ResponseAppsValidateRollbackError $error;
    /**
     * Contains a list of warnings that may cause the rollback to run under unideal circumstances.
     *
     * @var list<AppRollbackValidationCondition>
     */
    protected array $warnings;
    /**
     * Indicates whether the app can be rolled back to the specified deployment.
     *
     */
    public function getValid(): bool
    {
        return $this->valid;
    }
    /**
     * Indicates whether the app can be rolled back to the specified deployment.
     *
     *
     * @return self
     */
    public function setValid(bool $valid): self
    {
        $this->initialized['valid'] = true;
        $this->valid = $valid;
        return $this;
    }
    public function getError(): ResponseAppsValidateRollbackError
    {
        return $this->error;
    }
    public function setError(ResponseAppsValidateRollbackError $error): self
    {
        $this->initialized['error'] = true;
        $this->error = $error;
        return $this;
    }
    /**
     * Contains a list of warnings that may cause the rollback to run under unideal circumstances.
     *
     * @return list<AppRollbackValidationCondition>
     */
    public function getWarnings(): array
    {
        return $this->warnings;
    }
    /**
     * Contains a list of warnings that may cause the rollback to run under unideal circumstances.
     *
     * @param list<AppRollbackValidationCondition> $warnings
     *
     * @return self
     */
    public function setWarnings(array $warnings): self
    {
        $this->initialized['warnings'] = true;
        $this->warnings = $warnings;
        return $this;
    }
}