<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ResponseSshKeysAll extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var list<SshKeys>
     */
    protected array $sshKeys;
    protected PageLinks $links;
    protected MetaMeta $meta;
    /**
     * @return list<SshKeys>
     */
    public function getSshKeys(): array
    {
        return $this->sshKeys;
    }
    /**
     * @param list<SshKeys> $sshKeys
     */
    public function setSshKeys(array $sshKeys): self
    {
        $this->initialized['sshKeys'] = true;
        $this->sshKeys = $sshKeys;
        return $this;
    }
    public function getLinks(): PageLinks
    {
        return $this->links;
    }
    public function setLinks(PageLinks $links): self
    {
        $this->initialized['links'] = true;
        $this->links = $links;
        return $this;
    }
    public function getMeta(): MetaMeta
    {
        return $this->meta;
    }
    public function setMeta(MetaMeta $meta): self
    {
        $this->initialized['meta'] = true;
        $this->meta = $meta;
        return $this;
    }
}