<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ResponseReservedIpv6CreateReservedIpv6 extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The public IP address of the reserved IPv6. It also serves as its identifier.
     */
    protected string $ip;
    /**
     * The region that the reserved IPv6 is reserved to. When you query a reserved IPv6,the region_slug will be returned.
     */
    protected string $regionSlug;
    protected \DateTime $reservedAt;
    /**
     * The public IP address of the reserved IPv6. It also serves as its identifier.
     */
    public function getIp(): string
    {
        return $this->ip;
    }
    /**
     * The public IP address of the reserved IPv6. It also serves as its identifier.
     *
     * @return self
     */
    public function setIp(string $ip): self
    {
        $this->initialized['ip'] = true;
        $this->ip = $ip;
        return $this;
    }
    /**
     * The region that the reserved IPv6 is reserved to. When you query a reserved IPv6,the region_slug will be returned.
     */
    public function getRegionSlug(): string
    {
        return $this->regionSlug;
    }
    /**
     * The region that the reserved IPv6 is reserved to. When you query a reserved IPv6,the region_slug will be returned.
     *
     * @return self
     */
    public function setRegionSlug(string $regionSlug): self
    {
        $this->initialized['regionSlug'] = true;
        $this->regionSlug = $regionSlug;
        return $this;
    }
    public function getReservedAt(): \DateTime
    {
        return $this->reservedAt;
    }
    public function setReservedAt(\DateTime $reservedAt): self
    {
        $this->initialized['reservedAt'] = true;
        $this->reservedAt = $reservedAt;
        return $this;
    }
}