<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue669\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class TagsResource extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * An array of objects containing resource_id and resource_type
     * attributes.
     * 
     * This response will only include resources that you are authorized to see.
     * For example, to see Droplets, include the `droplet:read` scope.
     * 
     *
     * @var list<TagsResourceResourcesItem>
     */
    protected array $resources;
    /**
     * An array of objects containing resource_id and resource_type
     * attributes.
     * 
     * This response will only include resources that you are authorized to see.
     * For example, to see Droplets, include the `droplet:read` scope.
     * 
     *
     * @return list<TagsResourceResourcesItem>
     */
    public function getResources(): array
    {
        return $this->resources;
    }
    /**
     * An array of objects containing resource_id and resource_type
     * attributes.
     * 
     * This response will only include resources that you are authorized to see.
     * For example, to see Droplets, include the `droplet:read` scope.
     * 
     */
    public function setResources(TagsResourceResourcesItem ...$resources): self
    {
        $this->initialized['resources'] = true;
        $this->resources = array_values($resources);
        return $this;
    }
}