<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Exception;

class ReposReplaceAllTopicsUnprocessableEntityException extends UnprocessableEntityException
{
    private \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ValidationErrorSimple $validationErrorSimple;
    private \Psr\Http\Message\ResponseInterface $response;
    public function __construct(\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ValidationErrorSimple $validationErrorSimple, \Psr\Http\Message\ResponseInterface $response)
    {
        parent::__construct('Validation Failed');
        $this->validationErrorSimple = $validationErrorSimple;
        $this->response = $response;
    }
    public function getValidationErrorSimple(): \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ValidationErrorSimple
    {
        return $this->validationErrorSimple;
    }
    public function getResponse(): \Psr\Http\Message\ResponseInterface
    {
        return $this->response;
    }
}