<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class CommitCommit extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $url;
    protected ?CommitCommitAuthor $author;
    protected ?CommitCommitCommitter $committer;
    protected string $message;
    protected int $commentCount;
    protected CommitCommitTree $tree;
    protected mixed $verification;
    public function getUrl(): string
    {
        return $this->url;
    }
    public function setUrl(string $url): self
    {
        $this->initialized['url'] = true;
        $this->url = $url;
        return $this;
    }
    public function getAuthor(): ?CommitCommitAuthor
    {
        return $this->author;
    }
    public function setAuthor(?CommitCommitAuthor $author): self
    {
        $this->initialized['author'] = true;
        $this->author = $author;
        return $this;
    }
    public function getCommitter(): ?CommitCommitCommitter
    {
        return $this->committer;
    }
    public function setCommitter(?CommitCommitCommitter $committer): self
    {
        $this->initialized['committer'] = true;
        $this->committer = $committer;
        return $this;
    }
    public function getMessage(): string
    {
        return $this->message;
    }
    public function setMessage(string $message): self
    {
        $this->initialized['message'] = true;
        $this->message = $message;
        return $this;
    }
    public function getCommentCount(): int
    {
        return $this->commentCount;
    }
    public function setCommentCount(int $commentCount): self
    {
        $this->initialized['commentCount'] = true;
        $this->commentCount = $commentCount;
        return $this;
    }
    public function getTree(): CommitCommitTree
    {
        return $this->tree;
    }
    public function setTree(CommitCommitTree $tree): self
    {
        $this->initialized['tree'] = true;
        $this->tree = $tree;
        return $this;
    }
    public function getVerification(): mixed
    {
        return $this->verification;
    }
    public function setVerification(mixed $verification): self
    {
        $this->initialized['verification'] = true;
        $this->verification = $verification;
        return $this;
    }
}