<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ContributorActivityWeeksItem extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $w;
    protected int $a;
    protected int $d;
    protected int $c;
    public function getW(): string
    {
        return $this->w;
    }
    public function setW(string $w): self
    {
        $this->initialized['w'] = true;
        $this->w = $w;
        return $this;
    }
    public function getA(): int
    {
        return $this->a;
    }
    public function setA(int $a): self
    {
        $this->initialized['a'] = true;
        $this->a = $a;
        return $this;
    }
    public function getD(): int
    {
        return $this->d;
    }
    public function setD(int $d): self
    {
        $this->initialized['d'] = true;
        $this->d = $d;
        return $this;
    }
    public function getC(): int
    {
        return $this->c;
    }
    public function setC(int $c): self
    {
        $this->initialized['c'] = true;
        $this->c = $c;
        return $this;
    }
}