<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class GetResponse200 extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $currentUserUrl;
    protected string $currentUserAuthorizationsHtmlUrl;
    protected string $authorizationsUrl;
    protected string $codeSearchUrl;
    protected string $commitSearchUrl;
    protected string $emailsUrl;
    protected string $emojisUrl;
    protected string $eventsUrl;
    protected string $feedsUrl;
    protected string $followersUrl;
    protected string $followingUrl;
    protected string $gistsUrl;
    protected string $hubUrl;
    protected string $issueSearchUrl;
    protected string $issuesUrl;
    protected string $keysUrl;
    protected string $labelSearchUrl;
    protected string $notificationsUrl;
    protected string $organizationUrl;
    protected string $organizationRepositoriesUrl;
    protected string $organizationTeamsUrl;
    protected string $publicGistsUrl;
    protected string $rateLimitUrl;
    protected string $repositoryUrl;
    protected string $repositorySearchUrl;
    protected string $currentUserRepositoriesUrl;
    protected string $starredUrl;
    protected string $starredGistsUrl;
    protected string $topicSearchUrl;
    protected string $userUrl;
    protected string $userOrganizationsUrl;
    protected string $userRepositoriesUrl;
    protected string $userSearchUrl;
    public function getCurrentUserUrl(): string
    {
        return $this->currentUserUrl;
    }
    public function setCurrentUserUrl(string $currentUserUrl): self
    {
        $this->initialized['currentUserUrl'] = true;
        $this->currentUserUrl = $currentUserUrl;
        return $this;
    }
    public function getCurrentUserAuthorizationsHtmlUrl(): string
    {
        return $this->currentUserAuthorizationsHtmlUrl;
    }
    public function setCurrentUserAuthorizationsHtmlUrl(string $currentUserAuthorizationsHtmlUrl): self
    {
        $this->initialized['currentUserAuthorizationsHtmlUrl'] = true;
        $this->currentUserAuthorizationsHtmlUrl = $currentUserAuthorizationsHtmlUrl;
        return $this;
    }
    public function getAuthorizationsUrl(): string
    {
        return $this->authorizationsUrl;
    }
    public function setAuthorizationsUrl(string $authorizationsUrl): self
    {
        $this->initialized['authorizationsUrl'] = true;
        $this->authorizationsUrl = $authorizationsUrl;
        return $this;
    }
    public function getCodeSearchUrl(): string
    {
        return $this->codeSearchUrl;
    }
    public function setCodeSearchUrl(string $codeSearchUrl): self
    {
        $this->initialized['codeSearchUrl'] = true;
        $this->codeSearchUrl = $codeSearchUrl;
        return $this;
    }
    public function getCommitSearchUrl(): string
    {
        return $this->commitSearchUrl;
    }
    public function setCommitSearchUrl(string $commitSearchUrl): self
    {
        $this->initialized['commitSearchUrl'] = true;
        $this->commitSearchUrl = $commitSearchUrl;
        return $this;
    }
    public function getEmailsUrl(): string
    {
        return $this->emailsUrl;
    }
    public function setEmailsUrl(string $emailsUrl): self
    {
        $this->initialized['emailsUrl'] = true;
        $this->emailsUrl = $emailsUrl;
        return $this;
    }
    public function getEmojisUrl(): string
    {
        return $this->emojisUrl;
    }
    public function setEmojisUrl(string $emojisUrl): self
    {
        $this->initialized['emojisUrl'] = true;
        $this->emojisUrl = $emojisUrl;
        return $this;
    }
    public function getEventsUrl(): string
    {
        return $this->eventsUrl;
    }
    public function setEventsUrl(string $eventsUrl): self
    {
        $this->initialized['eventsUrl'] = true;
        $this->eventsUrl = $eventsUrl;
        return $this;
    }
    public function getFeedsUrl(): string
    {
        return $this->feedsUrl;
    }
    public function setFeedsUrl(string $feedsUrl): self
    {
        $this->initialized['feedsUrl'] = true;
        $this->feedsUrl = $feedsUrl;
        return $this;
    }
    public function getFollowersUrl(): string
    {
        return $this->followersUrl;
    }
    public function setFollowersUrl(string $followersUrl): self
    {
        $this->initialized['followersUrl'] = true;
        $this->followersUrl = $followersUrl;
        return $this;
    }
    public function getFollowingUrl(): string
    {
        return $this->followingUrl;
    }
    public function setFollowingUrl(string $followingUrl): self
    {
        $this->initialized['followingUrl'] = true;
        $this->followingUrl = $followingUrl;
        return $this;
    }
    public function getGistsUrl(): string
    {
        return $this->gistsUrl;
    }
    public function setGistsUrl(string $gistsUrl): self
    {
        $this->initialized['gistsUrl'] = true;
        $this->gistsUrl = $gistsUrl;
        return $this;
    }
    public function getHubUrl(): string
    {
        return $this->hubUrl;
    }
    public function setHubUrl(string $hubUrl): self
    {
        $this->initialized['hubUrl'] = true;
        $this->hubUrl = $hubUrl;
        return $this;
    }
    public function getIssueSearchUrl(): string
    {
        return $this->issueSearchUrl;
    }
    public function setIssueSearchUrl(string $issueSearchUrl): self
    {
        $this->initialized['issueSearchUrl'] = true;
        $this->issueSearchUrl = $issueSearchUrl;
        return $this;
    }
    public function getIssuesUrl(): string
    {
        return $this->issuesUrl;
    }
    public function setIssuesUrl(string $issuesUrl): self
    {
        $this->initialized['issuesUrl'] = true;
        $this->issuesUrl = $issuesUrl;
        return $this;
    }
    public function getKeysUrl(): string
    {
        return $this->keysUrl;
    }
    public function setKeysUrl(string $keysUrl): self
    {
        $this->initialized['keysUrl'] = true;
        $this->keysUrl = $keysUrl;
        return $this;
    }
    public function getLabelSearchUrl(): string
    {
        return $this->labelSearchUrl;
    }
    public function setLabelSearchUrl(string $labelSearchUrl): self
    {
        $this->initialized['labelSearchUrl'] = true;
        $this->labelSearchUrl = $labelSearchUrl;
        return $this;
    }
    public function getNotificationsUrl(): string
    {
        return $this->notificationsUrl;
    }
    public function setNotificationsUrl(string $notificationsUrl): self
    {
        $this->initialized['notificationsUrl'] = true;
        $this->notificationsUrl = $notificationsUrl;
        return $this;
    }
    public function getOrganizationUrl(): string
    {
        return $this->organizationUrl;
    }
    public function setOrganizationUrl(string $organizationUrl): self
    {
        $this->initialized['organizationUrl'] = true;
        $this->organizationUrl = $organizationUrl;
        return $this;
    }
    public function getOrganizationRepositoriesUrl(): string
    {
        return $this->organizationRepositoriesUrl;
    }
    public function setOrganizationRepositoriesUrl(string $organizationRepositoriesUrl): self
    {
        $this->initialized['organizationRepositoriesUrl'] = true;
        $this->organizationRepositoriesUrl = $organizationRepositoriesUrl;
        return $this;
    }
    public function getOrganizationTeamsUrl(): string
    {
        return $this->organizationTeamsUrl;
    }
    public function setOrganizationTeamsUrl(string $organizationTeamsUrl): self
    {
        $this->initialized['organizationTeamsUrl'] = true;
        $this->organizationTeamsUrl = $organizationTeamsUrl;
        return $this;
    }
    public function getPublicGistsUrl(): string
    {
        return $this->publicGistsUrl;
    }
    public function setPublicGistsUrl(string $publicGistsUrl): self
    {
        $this->initialized['publicGistsUrl'] = true;
        $this->publicGistsUrl = $publicGistsUrl;
        return $this;
    }
    public function getRateLimitUrl(): string
    {
        return $this->rateLimitUrl;
    }
    public function setRateLimitUrl(string $rateLimitUrl): self
    {
        $this->initialized['rateLimitUrl'] = true;
        $this->rateLimitUrl = $rateLimitUrl;
        return $this;
    }
    public function getRepositoryUrl(): string
    {
        return $this->repositoryUrl;
    }
    public function setRepositoryUrl(string $repositoryUrl): self
    {
        $this->initialized['repositoryUrl'] = true;
        $this->repositoryUrl = $repositoryUrl;
        return $this;
    }
    public function getRepositorySearchUrl(): string
    {
        return $this->repositorySearchUrl;
    }
    public function setRepositorySearchUrl(string $repositorySearchUrl): self
    {
        $this->initialized['repositorySearchUrl'] = true;
        $this->repositorySearchUrl = $repositorySearchUrl;
        return $this;
    }
    public function getCurrentUserRepositoriesUrl(): string
    {
        return $this->currentUserRepositoriesUrl;
    }
    public function setCurrentUserRepositoriesUrl(string $currentUserRepositoriesUrl): self
    {
        $this->initialized['currentUserRepositoriesUrl'] = true;
        $this->currentUserRepositoriesUrl = $currentUserRepositoriesUrl;
        return $this;
    }
    public function getStarredUrl(): string
    {
        return $this->starredUrl;
    }
    public function setStarredUrl(string $starredUrl): self
    {
        $this->initialized['starredUrl'] = true;
        $this->starredUrl = $starredUrl;
        return $this;
    }
    public function getStarredGistsUrl(): string
    {
        return $this->starredGistsUrl;
    }
    public function setStarredGistsUrl(string $starredGistsUrl): self
    {
        $this->initialized['starredGistsUrl'] = true;
        $this->starredGistsUrl = $starredGistsUrl;
        return $this;
    }
    public function getTopicSearchUrl(): string
    {
        return $this->topicSearchUrl;
    }
    public function setTopicSearchUrl(string $topicSearchUrl): self
    {
        $this->initialized['topicSearchUrl'] = true;
        $this->topicSearchUrl = $topicSearchUrl;
        return $this;
    }
    public function getUserUrl(): string
    {
        return $this->userUrl;
    }
    public function setUserUrl(string $userUrl): self
    {
        $this->initialized['userUrl'] = true;
        $this->userUrl = $userUrl;
        return $this;
    }
    public function getUserOrganizationsUrl(): string
    {
        return $this->userOrganizationsUrl;
    }
    public function setUserOrganizationsUrl(string $userOrganizationsUrl): self
    {
        $this->initialized['userOrganizationsUrl'] = true;
        $this->userOrganizationsUrl = $userOrganizationsUrl;
        return $this;
    }
    public function getUserRepositoriesUrl(): string
    {
        return $this->userRepositoriesUrl;
    }
    public function setUserRepositoriesUrl(string $userRepositoriesUrl): self
    {
        $this->initialized['userRepositoriesUrl'] = true;
        $this->userRepositoriesUrl = $userRepositoriesUrl;
        return $this;
    }
    public function getUserSearchUrl(): string
    {
        return $this->userSearchUrl;
    }
    public function setUserSearchUrl(string $userSearchUrl): self
    {
        $this->initialized['userSearchUrl'] = true;
        $this->userSearchUrl = $userSearchUrl;
        return $this;
    }
}