<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class RateLimit extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected int $limit;
    protected int $remaining;
    protected int $reset;
    public function getLimit(): int
    {
        return $this->limit;
    }
    public function setLimit(int $limit): self
    {
        $this->initialized['limit'] = true;
        $this->limit = $limit;
        return $this;
    }
    public function getRemaining(): int
    {
        return $this->remaining;
    }
    public function setRemaining(int $remaining): self
    {
        $this->initialized['remaining'] = true;
        $this->remaining = $remaining;
        return $this;
    }
    public function getReset(): int
    {
        return $this->reset;
    }
    public function setReset(int $reset): self
    {
        $this->initialized['reset'] = true;
        $this->reset = $reset;
        return $this;
    }
}