<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ReposOwnerRepoCheckRunsCheckRunIdPatchBodyActionsItem extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The text to be displayed on a button in the web UI. The maximum size is 20 characters.
     */
    protected string $label;
    /**
     * A short explanation of what this action would do. The maximum size is 40 characters.
     */
    protected string $description;
    /**
     * A reference for the action on the integrator's system. The maximum size is 20 characters.
     */
    protected string $identifier;
    /**
     * The text to be displayed on a button in the web UI. The maximum size is 20 characters.
     */
    public function getLabel(): string
    {
        return $this->label;
    }
    /**
     * The text to be displayed on a button in the web UI. The maximum size is 20 characters.
     */
    public function setLabel(string $label): self
    {
        $this->initialized['label'] = true;
        $this->label = $label;
        return $this;
    }
    /**
     * A short explanation of what this action would do. The maximum size is 40 characters.
     */
    public function getDescription(): string
    {
        return $this->description;
    }
    /**
     * A short explanation of what this action would do. The maximum size is 40 characters.
     */
    public function setDescription(string $description): self
    {
        $this->initialized['description'] = true;
        $this->description = $description;
        return $this;
    }
    /**
     * A reference for the action on the integrator's system. The maximum size is 20 characters.
     */
    public function getIdentifier(): string
    {
        return $this->identifier;
    }
    /**
     * A reference for the action on the integrator's system. The maximum size is 20 characters.
     */
    public function setIdentifier(string $identifier): self
    {
        $this->initialized['identifier'] = true;
        $this->identifier = $identifier;
        return $this;
    }
}