<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ReposOwnerRepoMergesPostBody extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The name of the base branch that the head will be merged into.
     */
    protected string $base;
    /**
     * The head to merge. This can be a branch name or a commit SHA1.
     */
    protected string $head;
    /**
     * Commit message to use for the merge commit. If omitted, a default message will be used.
     */
    protected string $commitMessage;
    /**
     * The name of the base branch that the head will be merged into.
     */
    public function getBase(): string
    {
        return $this->base;
    }
    /**
     * The name of the base branch that the head will be merged into.
     *
     * @return self
     */
    public function setBase(string $base): self
    {
        $this->initialized['base'] = true;
        $this->base = $base;
        return $this;
    }
    /**
     * The head to merge. This can be a branch name or a commit SHA1.
     */
    public function getHead(): string
    {
        return $this->head;
    }
    /**
     * The head to merge. This can be a branch name or a commit SHA1.
     *
     * @return self
     */
    public function setHead(string $head): self
    {
        $this->initialized['head'] = true;
        $this->head = $head;
        return $this;
    }
    /**
     * Commit message to use for the merge commit. If omitted, a default message will be used.
     */
    public function getCommitMessage(): string
    {
        return $this->commitMessage;
    }
    /**
     * Commit message to use for the merge commit. If omitted, a default message will be used.
     *
     * @return self
     */
    public function setCommitMessage(string $commitMessage): self
    {
        $this->initialized['commitMessage'] = true;
        $this->commitMessage = $commitMessage;
        return $this;
    }
}