<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ScimV2OrganizationsOrgUsersScimUserIdPutBodyName extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $givenName;
    protected string $familyName;
    public function getGivenName(): string
    {
        return $this->givenName;
    }
    public function setGivenName(string $givenName): self
    {
        $this->initialized['givenName'] = true;
        $this->givenName = $givenName;
        return $this;
    }
    public function getFamilyName(): string
    {
        return $this->familyName;
    }
    public function setFamilyName(string $familyName): self
    {
        $this->initialized['familyName'] = true;
        $this->familyName = $familyName;
        return $this;
    }
}