<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class UserMigrationsPostBody extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Lock the repositories being migrated at the start of the migration
     */
    protected bool $lockRepositories;
    /**
     * Do not include attachments in the migration
     */
    protected bool $excludeAttachments;
    /**
     * Exclude attributes from the API response to improve performance
     *
     * @var list<string>
     */
    protected array $exclude;
    /**
     * @var list<string>
     */
    protected array $repositories;
    /**
     * Lock the repositories being migrated at the start of the migration
     */
    public function getLockRepositories(): bool
    {
        return $this->lockRepositories;
    }
    /**
     * Lock the repositories being migrated at the start of the migration
     */
    public function setLockRepositories(bool $lockRepositories): self
    {
        $this->initialized['lockRepositories'] = true;
        $this->lockRepositories = $lockRepositories;
        return $this;
    }
    /**
     * Do not include attachments in the migration
     */
    public function getExcludeAttachments(): bool
    {
        return $this->excludeAttachments;
    }
    /**
     * Do not include attachments in the migration
     */
    public function setExcludeAttachments(bool $excludeAttachments): self
    {
        $this->initialized['excludeAttachments'] = true;
        $this->excludeAttachments = $excludeAttachments;
        return $this;
    }
    /**
     * Exclude attributes from the API response to improve performance
     *
     * @return list<string>
     */
    public function getExclude(): array
    {
        return $this->exclude;
    }
    /**
     * Exclude attributes from the API response to improve performance
     */
    public function setExclude(string ...$exclude): self
    {
        $this->initialized['exclude'] = true;
        $this->exclude = array_values($exclude);
        return $this;
    }
    /**
     * @return list<string>
     */
    public function getRepositories(): array
    {
        return $this->repositories;
    }
    public function setRepositories(string ...$repositories): self
    {
        $this->initialized['repositories'] = true;
        $this->repositories = array_values($repositories);
        return $this;
    }
}