<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class AggregationFilter extends FilterBase
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The name of the aggregation this filter is connected to.
     *
     */
    protected ?string $aggregationName;
    /**
     * The filter to be applied.
     *
     */
    protected mixed $filter;
    /**
     * Autogenerated Guid at request time, for precise aggregation result mapping.
     *
     */
    protected ?string $temporaryAggregatorRequestId;
    /**
     * The name of the aggregation this filter is connected to.
     *
     */
    public function getAggregationName(): ?string
    {
        return $this->aggregationName;
    }
    /**
     * The name of the aggregation this filter is connected to.
     *
     *
     * @return self
     */
    public function setAggregationName(?string $aggregationName): self
    {
        $this->initialized['aggregationName'] = true;
        $this->aggregationName = $aggregationName;
        return $this;
    }
    /**
     * The filter to be applied.
     *
     */
    public function getFilter(): mixed
    {
        return $this->filter;
    }
    /**
     * The filter to be applied.
     *
     *
     * @return self
     */
    public function setFilter(mixed $filter): self
    {
        $this->initialized['filter'] = true;
        $this->filter = $filter;
        return $this;
    }
    /**
     * Autogenerated Guid at request time, for precise aggregation result mapping.
     *
     */
    public function getTemporaryAggregatorRequestId(): ?string
    {
        return $this->temporaryAggregatorRequestId;
    }
    /**
     * Autogenerated Guid at request time, for precise aggregation result mapping.
     *
     *
     * @return self
     */
    public function setTemporaryAggregatorRequestId(?string $temporaryAggregatorRequestId): self
    {
        $this->initialized['temporaryAggregatorRequestId'] = true;
        $this->temporaryAggregatorRequestId = $temporaryAggregatorRequestId;
        return $this;
    }
}