<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class BusinessProcessStateChangeRequest
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The new state of the business process.
     */
    protected string $state;
    /**
     * The new life cycle of the business process.
     */
    protected mixed $lifeCycle = null;
    /**
     * An optional notification update to be posted together with the transition.
     */
    protected mixed $notification = null;
    /**
     * The new state of the business process.
     */
    public function getState(): string
    {
        return $this->state;
    }
    /**
     * The new state of the business process.
     */
    public function setState(string $state): self
    {
        $this->initialized['state'] = true;
        $this->state = $state;
        return $this;
    }
    /**
     * The new life cycle of the business process.
     */
    public function getLifeCycle(): mixed
    {
        return $this->lifeCycle;
    }
    /**
     * The new life cycle of the business process.
     */
    public function setLifeCycle(mixed $lifeCycle): self
    {
        $this->initialized['lifeCycle'] = true;
        $this->lifeCycle = $lifeCycle;
        return $this;
    }
    /**
     * An optional notification update to be posted together with the transition.
     */
    public function getNotification(): mixed
    {
        return $this->notification;
    }
    /**
     * An optional notification update to be posted together with the transition.
     */
    public function setNotification(mixed $notification): self
    {
        $this->initialized['notification'] = true;
        $this->notification = $notification;
        return $this;
    }
}