<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class BusinessProcessNotificationUpdate
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The title the message that is shown to the user should have.
     */
    protected mixed $title = null;
    /**
     * The message shown to the user.
     */
    protected mixed $message = null;
    /**
     * An optional navigation link that allows the user to jump to a page giving more information
     * about the process.
     */
    protected ?string $navigationLink = null;
    /**
     * The event type of the notification.
     */
    protected mixed $eventType = null;
    /**
     * The title the message that is shown to the user should have.
     */
    public function getTitle(): mixed
    {
        return $this->title;
    }
    /**
     * The title the message that is shown to the user should have.
     *
     * @return self
     */
    public function setTitle(mixed $title): self
    {
        $this->initialized['title'] = true;
        $this->title = $title;
        return $this;
    }
    /**
     * The message shown to the user.
     */
    public function getMessage(): mixed
    {
        return $this->message;
    }
    /**
     * The message shown to the user.
     *
     * @return self
     */
    public function setMessage(mixed $message): self
    {
        $this->initialized['message'] = true;
        $this->message = $message;
        return $this;
    }
    /**
     * An optional navigation link that allows the user to jump to a page giving more information
     * about the process.
     */
    public function getNavigationLink(): ?string
    {
        return $this->navigationLink;
    }
    /**
     * An optional navigation link that allows the user to jump to a page giving more information
     * about the process.
     *
     * @return self
     */
    public function setNavigationLink(?string $navigationLink): self
    {
        $this->initialized['navigationLink'] = true;
        $this->navigationLink = $navigationLink;
        return $this;
    }
    /**
     * The event type of the notification.
     */
    public function getEventType(): mixed
    {
        return $this->eventType;
    }
    /**
     * The event type of the notification.
     *
     * @return self
     */
    public function setEventType(mixed $eventType): self
    {
        $this->initialized['eventType'] = true;
        $this->eventType = $eventType;
        return $this;
    }
}