<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class ContentManyReferencesRequest
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The IDs of the contents whose references need to be retrieved.
     *
     * @var list<string>
     */
    protected array $contentIds;
    /**
     * Limits the number of the returned metadata references by setting paging information.
     */
    protected mixed $references = null;
    /**
     * Limits the number of the returned share references by setting paging information.
     */
    protected mixed $shares = null;
    /**
     * The IDs of the contents whose references need to be retrieved.
     *
     * @return list<string>
     */
    public function getContentIds(): array
    {
        return $this->contentIds;
    }
    /**
     * The IDs of the contents whose references need to be retrieved.
     */
    public function setContentIds(string ...$contentIds): self
    {
        $this->initialized['contentIds'] = true;
        $this->contentIds = array_values($contentIds);
        return $this;
    }
    /**
     * Limits the number of the returned metadata references by setting paging information.
     */
    public function getReferences(): mixed
    {
        return $this->references;
    }
    /**
     * Limits the number of the returned metadata references by setting paging information.
     */
    public function setReferences(mixed $references): self
    {
        $this->initialized['references'] = true;
        $this->references = $references;
        return $this;
    }
    /**
     * Limits the number of the returned share references by setting paging information.
     */
    public function getShares(): mixed
    {
        return $this->shares;
    }
    /**
     * Limits the number of the returned share references by setting paging information.
     */
    public function setShares(mixed $shares): self
    {
        $this->initialized['shares'] = true;
        $this->shares = $shares;
        return $this;
    }
}