<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class DateRangeForAggregator
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Language specific range names.
     *
     */
    protected mixed $names;
    /**
     * The from value: it can be a datetime string or a pattern now(+-)(int)(YMDHm).
     *
     */
    protected ?string $from;
    /**
     * The to value: it can be a datetime string or a pattern now(+-)(int)(YMDHm).
     *
     */
    protected ?string $to;
    /**
     * Language specific range names.
     *
     */
    public function getNames(): mixed
    {
        return $this->names;
    }
    /**
     * Language specific range names.
     *
     *
     * @return self
     */
    public function setNames(mixed $names): self
    {
        $this->initialized['names'] = true;
        $this->names = $names;
        return $this;
    }
    /**
     * The from value: it can be a datetime string or a pattern now(+-)(int)(YMDHm).
     *
     */
    public function getFrom(): ?string
    {
        return $this->from;
    }
    /**
     * The from value: it can be a datetime string or a pattern now(+-)(int)(YMDHm).
     *
     *
     * @return self
     */
    public function setFrom(?string $from): self
    {
        $this->initialized['from'] = true;
        $this->from = $from;
        return $this;
    }
    /**
     * The to value: it can be a datetime string or a pattern now(+-)(int)(YMDHm).
     *
     */
    public function getTo(): ?string
    {
        return $this->to;
    }
    /**
     * The to value: it can be a datetime string or a pattern now(+-)(int)(YMDHm).
     *
     *
     * @return self
     */
    public function setTo(?string $to): self
    {
        $this->initialized['to'] = true;
        $this->to = $to;
        return $this;
    }
}