<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ElasticVersionUpdateException extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $traceLevel;
    protected ?string $traceId;
    protected ?string $traceJobId;
    protected int $httpStatusCode;
    protected ?string $exceptionMessage;
    protected string $kind;
    protected ?string $expectedVersion;
    protected ?string $actualVersion;
    public function getTraceLevel(): string
    {
        return $this->traceLevel;
    }
    public function setTraceLevel(string $traceLevel): self
    {
        $this->initialized['traceLevel'] = true;
        $this->traceLevel = $traceLevel;
        return $this;
    }
    public function getTraceId(): ?string
    {
        return $this->traceId;
    }
    public function setTraceId(?string $traceId): self
    {
        $this->initialized['traceId'] = true;
        $this->traceId = $traceId;
        return $this;
    }
    public function getTraceJobId(): ?string
    {
        return $this->traceJobId;
    }
    public function setTraceJobId(?string $traceJobId): self
    {
        $this->initialized['traceJobId'] = true;
        $this->traceJobId = $traceJobId;
        return $this;
    }
    public function getHttpStatusCode(): int
    {
        return $this->httpStatusCode;
    }
    public function setHttpStatusCode(int $httpStatusCode): self
    {
        $this->initialized['httpStatusCode'] = true;
        $this->httpStatusCode = $httpStatusCode;
        return $this;
    }
    public function getExceptionMessage(): ?string
    {
        return $this->exceptionMessage;
    }
    public function setExceptionMessage(?string $exceptionMessage): self
    {
        $this->initialized['exceptionMessage'] = true;
        $this->exceptionMessage = $exceptionMessage;
        return $this;
    }
    public function getKind(): string
    {
        return $this->kind;
    }
    public function setKind(string $kind): self
    {
        $this->initialized['kind'] = true;
        $this->kind = $kind;
        return $this;
    }
    public function getExpectedVersion(): ?string
    {
        return $this->expectedVersion;
    }
    public function setExpectedVersion(?string $expectedVersion): self
    {
        $this->initialized['expectedVersion'] = true;
        $this->expectedVersion = $expectedVersion;
        return $this;
    }
    public function getActualVersion(): ?string
    {
        return $this->actualVersion;
    }
    public function setActualVersion(?string $actualVersion): self
    {
        $this->initialized['actualVersion'] = true;
        $this->actualVersion = $actualVersion;
        return $this;
    }
}