<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class GeoPointWithinPolygonCondition extends BusinessRuleCondition
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * JSON path to the field
     *
     */
    protected ?string $fieldPath;
    /**
     * List of points that form the polygon for the geo fence.
     * Must include at least 3 points.
     *
     * @var list<LatLon>|null
     */
    protected ?array $polygon;
    /**
     * JSON path to the field
     *
     */
    public function getFieldPath(): ?string
    {
        return $this->fieldPath;
    }
    /**
     * JSON path to the field
     *
     *
     * @return self
     */
    public function setFieldPath(?string $fieldPath): self
    {
        $this->initialized['fieldPath'] = true;
        $this->fieldPath = $fieldPath;
        return $this;
    }
    /**
     * List of points that form the polygon for the geo fence.
     * Must include at least 3 points.
     *
     * @return list<LatLon>|null
     */
    public function getPolygon(): ?array
    {
        return $this->polygon;
    }
    /**
    * List of points that form the polygon for the geo fence.
    Must include at least 3 points.
    *
    * @param list<LatLon>|null $polygon
    *
    * @return self
    */
    public function setPolygon(?array $polygon): self
    {
        $this->initialized['polygon'] = true;
        $this->polygon = $polygon;
        return $this;
    }
}