<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class ListItemUpdateManyRequest
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Allows updating list items with references to list items or contents that don't exist in the system.
     */
    protected bool $allowMissingDependencies;
    /**
     * Items to be updated.
     *
     * @var list<ListItemUpdateItem>
     */
    protected array $items;
    /**
     * Allows updating list items with references to list items or contents that don't exist in the system.
     */
    public function getAllowMissingDependencies(): bool
    {
        return $this->allowMissingDependencies;
    }
    /**
     * Allows updating list items with references to list items or contents that don't exist in the system.
     */
    public function setAllowMissingDependencies(bool $allowMissingDependencies): self
    {
        $this->initialized['allowMissingDependencies'] = true;
        $this->allowMissingDependencies = $allowMissingDependencies;
        return $this;
    }
    /**
     * Items to be updated.
     *
     * @return list<ListItemUpdateItem>
     */
    public function getItems(): array
    {
        return $this->items;
    }
    /**
     * Items to be updated.
     *
     * @param list<ListItemUpdateItem> $items
     */
    public function setItems(array $items): self
    {
        $this->initialized['items'] = true;
        $this->items = $items;
        return $this;
    }
}