<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class MetadataReference
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Target ID of reference.
     *
     */
    protected string $targetMetadataItemId;
    /**
     * Indicates if the source of the reference is restricted because of permissions.
     * If this is true and the SourceMetadataItemId property is filled, the user does not have the
     * edit permission on the source metadata item. If the SourceMetadataItemId is null, the user also
     * does not have the view permission on that item.
     *
     */
    protected bool $isRestricted;
    /**
     * ID of the source of the reference.
     *
     */
    protected ?string $sourceMetadataItemId;
    /**
     * DocType of the source of the reference.
     *
     */
    protected ?string $sourceDocType;
    /**
     * Target ID of reference.
     *
     */
    public function getTargetMetadataItemId(): string
    {
        return $this->targetMetadataItemId;
    }
    /**
     * Target ID of reference.
     *
     *
     * @return self
     */
    public function setTargetMetadataItemId(string $targetMetadataItemId): self
    {
        $this->initialized['targetMetadataItemId'] = true;
        $this->targetMetadataItemId = $targetMetadataItemId;
        return $this;
    }
    /**
     * Indicates if the source of the reference is restricted because of permissions.
     * If this is true and the SourceMetadataItemId property is filled, the user does not have the
     * edit permission on the source metadata item. If the SourceMetadataItemId is null, the user also
     * does not have the view permission on that item.
     *
     */
    public function getIsRestricted(): bool
    {
        return $this->isRestricted;
    }
    /**
    * Indicates if the source of the reference is restricted because of permissions.
    If this is true and the SourceMetadataItemId property is filled, the user does not have the
    edit permission on the source metadata item. If the SourceMetadataItemId is null, the user also
    does not have the view permission on that item.
    *
    *
    * @return self
    */
    public function setIsRestricted(bool $isRestricted): self
    {
        $this->initialized['isRestricted'] = true;
        $this->isRestricted = $isRestricted;
        return $this;
    }
    /**
     * ID of the source of the reference.
     *
     */
    public function getSourceMetadataItemId(): ?string
    {
        return $this->sourceMetadataItemId;
    }
    /**
     * ID of the source of the reference.
     *
     *
     * @return self
     */
    public function setSourceMetadataItemId(?string $sourceMetadataItemId): self
    {
        $this->initialized['sourceMetadataItemId'] = true;
        $this->sourceMetadataItemId = $sourceMetadataItemId;
        return $this;
    }
    /**
     * DocType of the source of the reference.
     *
     */
    public function getSourceDocType(): ?string
    {
        return $this->sourceDocType;
    }
    /**
     * DocType of the source of the reference.
     *
     *
     * @return self
     */
    public function setSourceDocType(?string $sourceDocType): self
    {
        $this->initialized['sourceDocType'] = true;
        $this->sourceDocType = $sourceDocType;
        return $this;
    }
}