<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class Mp4VideoFormat extends FormatBase
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Allows resizing of the video.
     *
     */
    protected mixed $resizeAction;
    /**
     * Gets or sets the encoding audio codec.
     *
     */
    protected mixed $audioCodec;
    /**
     * Gets or sets the encoding codec preset.
     *
     */
    protected mixed $preset;
    protected ?string $extension;
    /**
     * Allows resizing of the video.
     *
     */
    public function getResizeAction(): mixed
    {
        return $this->resizeAction;
    }
    /**
     * Allows resizing of the video.
     *
     *
     * @return self
     */
    public function setResizeAction(mixed $resizeAction): self
    {
        $this->initialized['resizeAction'] = true;
        $this->resizeAction = $resizeAction;
        return $this;
    }
    /**
     * Gets or sets the encoding audio codec.
     *
     */
    public function getAudioCodec(): mixed
    {
        return $this->audioCodec;
    }
    /**
     * Gets or sets the encoding audio codec.
     *
     *
     * @return self
     */
    public function setAudioCodec(mixed $audioCodec): self
    {
        $this->initialized['audioCodec'] = true;
        $this->audioCodec = $audioCodec;
        return $this;
    }
    /**
     * Gets or sets the encoding codec preset.
     *
     */
    public function getPreset(): mixed
    {
        return $this->preset;
    }
    /**
     * Gets or sets the encoding codec preset.
     *
     *
     * @return self
     */
    public function setPreset(mixed $preset): self
    {
        $this->initialized['preset'] = true;
        $this->preset = $preset;
        return $this;
    }
    public function getExtension(): ?string
    {
        return $this->extension;
    }
    public function setExtension(?string $extension): self
    {
        $this->initialized['extension'] = true;
        $this->extension = $extension;
        return $this;
    }
}