<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class NestedFilter extends FilterBase
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The path pointing to the nested document (i.e. personLayer.nestedAddress).
     *
     */
    protected string $path;
    /**
     * The filter to be applied on the nested documents.
     *
     */
    protected mixed $filter;
    /**
     * The path pointing to the nested document (i.e. personLayer.nestedAddress).
     *
     */
    public function getPath(): string
    {
        return $this->path;
    }
    /**
     * The path pointing to the nested document (i.e. personLayer.nestedAddress).
     *
     *
     * @return self
     */
    public function setPath(string $path): self
    {
        $this->initialized['path'] = true;
        $this->path = $path;
        return $this;
    }
    /**
     * The filter to be applied on the nested documents.
     *
     */
    public function getFilter(): mixed
    {
        return $this->filter;
    }
    /**
     * The filter to be applied on the nested documents.
     *
     *
     * @return self
     */
    public function setFilter(mixed $filter): self
    {
        $this->initialized['filter'] = true;
        $this->filter = $filter;
        return $this;
    }
}