<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class OrCondition extends BusinessRuleCondition
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The conditions.
     *
     * @var list<BusinessRuleCondition>|null
     */
    protected ?array $conditions = null;
    /**
     * The conditions.
     *
     * @return list<BusinessRuleCondition>|null
     */
    public function getConditions(): ?array
    {
        return $this->conditions;
    }
    /**
     * The conditions.
     *
     * @param list<BusinessRuleCondition>|null $conditions
     */
    public function setConditions(?array $conditions): self
    {
        $this->initialized['conditions'] = true;
        $this->conditions = $conditions;
        return $this;
    }
}