<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class PermissionSet
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The permission set ID.
     *
     */
    protected string $id;
    /**
     * When true this permission set will derogate all other configured permission sets.
     * Cannot be changed after creation.
     *
     */
    protected bool $exclusive;
    /**
     * Language specific permission set names.
     *
     */
    protected mixed $names = null;
    /**
     * The permission set ID.
     *
     */
    public function getId(): string
    {
        return $this->id;
    }
    /**
     * The permission set ID.
     *
     *
     * @return self
     */
    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;
        return $this;
    }
    /**
     * When true this permission set will derogate all other configured permission sets.
     * Cannot be changed after creation.
     *
     */
    public function getExclusive(): bool
    {
        return $this->exclusive;
    }
    /**
    * When true this permission set will derogate all other configured permission sets.
    Cannot be changed after creation.
    *
    *
    * @return self
    */
    public function setExclusive(bool $exclusive): self
    {
        $this->initialized['exclusive'] = true;
        $this->exclusive = $exclusive;
        return $this;
    }
    /**
     * Language specific permission set names.
     *
     */
    public function getNames(): mixed
    {
        return $this->names;
    }
    /**
     * Language specific permission set names.
     *
     *
     * @return self
     */
    public function setNames(mixed $names): self
    {
        $this->initialized['names'] = true;
        $this->names = $names;
        return $this;
    }
}