<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class SchemaImportRequest
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * ID of the file transfer identifying the file previously uploaded.
     */
    protected string $fileTransferId;
    /**
     * Allow creating list items that refer to list items or contents that don't exist in the system.
     */
    protected bool $allowMissingDependencies;
    /**
     * Import the list items belonging to the schema.
     */
    protected bool $importListItems;
    /**
     * ID of the file transfer identifying the file previously uploaded.
     */
    public function getFileTransferId(): string
    {
        return $this->fileTransferId;
    }
    /**
     * ID of the file transfer identifying the file previously uploaded.
     *
     * @return self
     */
    public function setFileTransferId(string $fileTransferId): self
    {
        $this->initialized['fileTransferId'] = true;
        $this->fileTransferId = $fileTransferId;
        return $this;
    }
    /**
     * Allow creating list items that refer to list items or contents that don't exist in the system.
     */
    public function getAllowMissingDependencies(): bool
    {
        return $this->allowMissingDependencies;
    }
    /**
     * Allow creating list items that refer to list items or contents that don't exist in the system.
     *
     * @return self
     */
    public function setAllowMissingDependencies(bool $allowMissingDependencies): self
    {
        $this->initialized['allowMissingDependencies'] = true;
        $this->allowMissingDependencies = $allowMissingDependencies;
        return $this;
    }
    /**
     * Import the list items belonging to the schema.
     */
    public function getImportListItems(): bool
    {
        return $this->importListItems;
    }
    /**
     * Import the list items belonging to the schema.
     *
     * @return self
     */
    public function setImportListItems(bool $importListItems): self
    {
        $this->initialized['importListItems'] = true;
        $this->importListItems = $importListItems;
        return $this;
    }
}