<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class SchemaUpdateManyRequest
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The schemas to update.
     *
     * @var list<SchemaUpdateItem>
     */
    protected array $schemas;
    /**
     * The schemas to update.
     *
     * @return list<SchemaUpdateItem>
     */
    public function getSchemas(): array
    {
        return $this->schemas;
    }
    /**
     * The schemas to update.
     *
     * @param list<SchemaUpdateItem> $schemas
     *
     * @return self
     */
    public function setSchemas(array $schemas): self
    {
        $this->initialized['schemas'] = true;
        $this->schemas = $schemas;
        return $this;
    }
}