<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

class TaggingOptionsBase
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Override for the output format ID to tag.
     *
     */
    protected ?string $tagOutputFormatId = null;
    /**
     * Override for the cache to use.
     *
     */
    protected ?string $keywordLookupCacheName = null;
    /**
     * Override for the layer to assign.
     *
     */
    protected ?string $taggingLayerId = null;
    /**
     * Override for the field id where found tags are stored.
     *
     */
    protected ?string $foundTagsFieldId = null;
    /**
     * Override for the field id where not found tags are stored.
     *
     */
    protected ?string $missingKeywordsFieldId = null;
    protected string $kind;
    /**
     * Override for the output format ID to tag.
     *
     */
    public function getTagOutputFormatId(): ?string
    {
        return $this->tagOutputFormatId;
    }
    /**
     * Override for the output format ID to tag.
     *
     */
    public function setTagOutputFormatId(?string $tagOutputFormatId): void
    {
        $this->initialized['tagOutputFormatId'] = true;
        $this->tagOutputFormatId = $tagOutputFormatId;
    }
    /**
     * Override for the cache to use.
     *
     */
    public function getKeywordLookupCacheName(): ?string
    {
        return $this->keywordLookupCacheName;
    }
    /**
     * Override for the cache to use.
     *
     */
    public function setKeywordLookupCacheName(?string $keywordLookupCacheName): void
    {
        $this->initialized['keywordLookupCacheName'] = true;
        $this->keywordLookupCacheName = $keywordLookupCacheName;
    }
    /**
     * Override for the layer to assign.
     *
     */
    public function getTaggingLayerId(): ?string
    {
        return $this->taggingLayerId;
    }
    /**
     * Override for the layer to assign.
     *
     */
    public function setTaggingLayerId(?string $taggingLayerId): void
    {
        $this->initialized['taggingLayerId'] = true;
        $this->taggingLayerId = $taggingLayerId;
    }
    /**
     * Override for the field id where found tags are stored.
     *
     */
    public function getFoundTagsFieldId(): ?string
    {
        return $this->foundTagsFieldId;
    }
    /**
     * Override for the field id where found tags are stored.
     *
     */
    public function setFoundTagsFieldId(?string $foundTagsFieldId): void
    {
        $this->initialized['foundTagsFieldId'] = true;
        $this->foundTagsFieldId = $foundTagsFieldId;
    }
    /**
     * Override for the field id where not found tags are stored.
     *
     */
    public function getMissingKeywordsFieldId(): ?string
    {
        return $this->missingKeywordsFieldId;
    }
    /**
     * Override for the field id where not found tags are stored.
     *
     */
    public function setMissingKeywordsFieldId(?string $missingKeywordsFieldId): void
    {
        $this->initialized['missingKeywordsFieldId'] = true;
        $this->missingKeywordsFieldId = $missingKeywordsFieldId;
    }
    public function getKind(): string
    {
        return $this->kind;
    }
    public function setKind(string $kind): void
    {
        $this->initialized['kind'] = true;
        $this->kind = $kind;
    }
}