<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class UserDetail extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * User's Picturepark ID.
     *
     */
    protected ?string $id;
    /**
     * User's first name.
     *
     */
    protected ?string $firstName;
    /**
     * User's last name.
     *
     */
    protected ?string $lastName;
    /**
     * Email address of the user (doubles as username).
     *
     */
    protected string $emailAddress;
    /**
     * Marks a user that was deleted from the system.
     *
     */
    protected bool $isDeleted;
    /**
     * User roles the user should be assigned to. Overwrites the original user roles.
     *
     * @var list<UserRoleAssignment>|null
     */
    protected ?array $userRoles;
    /**
     * Comment saved for the user.
     *
     */
    protected ?string $comment;
    /**
     * Preferred language, e.g. for correspondence.
     *
     */
    protected ?string $languageCode;
    /**
     * User's address.
     *
     */
    protected mixed $address;
    /**
     * Identity provider that governs this user or null for Picturepark's own IdentityServer.
     *
     */
    protected ?string $identityProviderId;
    /**
     * Owner tokens referencing the user.
     *
     * @var list<OwnerToken>|null
     */
    protected ?array $ownerTokens;
    /**
     * Authorization state the user is currently in.
     *
     */
    protected mixed $authorizationState;
    /**
     * Locked users are unable to log in and use the system.
     *
     */
    protected bool $isLocked;
    /**
     * Life cycle state the user is currently in.
     *
     */
    protected mixed $lifeCycle;
    /**
     * The support user is a user created for Picturepark support personnel.
     *
     */
    protected bool $isSupportUser;
    /**
     * Read-only users can't be removed from the system, e.g. service user.
     *
     */
    protected bool $isReadOnly;
    /**
     * Federated user is a user who is (currently) governed by an external identity provider.
     *
     */
    protected bool $isFederated;
    /**
     * Audit information.
     *
     */
    protected mixed $audit;
    /**
     * User's Picturepark ID.
     *
     */
    public function getId(): ?string
    {
        return $this->id;
    }
    /**
     * User's Picturepark ID.
     *
     *
     * @return self
     */
    public function setId(?string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;
        return $this;
    }
    /**
     * User's first name.
     *
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }
    /**
     * User's first name.
     *
     *
     * @return self
     */
    public function setFirstName(?string $firstName): self
    {
        $this->initialized['firstName'] = true;
        $this->firstName = $firstName;
        return $this;
    }
    /**
     * User's last name.
     *
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }
    /**
     * User's last name.
     *
     *
     * @return self
     */
    public function setLastName(?string $lastName): self
    {
        $this->initialized['lastName'] = true;
        $this->lastName = $lastName;
        return $this;
    }
    /**
     * Email address of the user (doubles as username).
     *
     */
    public function getEmailAddress(): string
    {
        return $this->emailAddress;
    }
    /**
     * Email address of the user (doubles as username).
     *
     *
     * @return self
     */
    public function setEmailAddress(string $emailAddress): self
    {
        $this->initialized['emailAddress'] = true;
        $this->emailAddress = $emailAddress;
        return $this;
    }
    /**
     * Marks a user that was deleted from the system.
     *
     */
    public function getIsDeleted(): bool
    {
        return $this->isDeleted;
    }
    /**
     * Marks a user that was deleted from the system.
     *
     *
     * @return self
     */
    public function setIsDeleted(bool $isDeleted): self
    {
        $this->initialized['isDeleted'] = true;
        $this->isDeleted = $isDeleted;
        return $this;
    }
    /**
     * User roles the user should be assigned to. Overwrites the original user roles.
     *
     * @return list<UserRoleAssignment>|null
     */
    public function getUserRoles(): ?array
    {
        return $this->userRoles;
    }
    /**
     * User roles the user should be assigned to. Overwrites the original user roles.
     *
     * @param list<UserRoleAssignment>|null $userRoles
     *
     * @return self
     */
    public function setUserRoles(?array $userRoles): self
    {
        $this->initialized['userRoles'] = true;
        $this->userRoles = $userRoles;
        return $this;
    }
    /**
     * Comment saved for the user.
     *
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }
    /**
     * Comment saved for the user.
     *
     *
     * @return self
     */
    public function setComment(?string $comment): self
    {
        $this->initialized['comment'] = true;
        $this->comment = $comment;
        return $this;
    }
    /**
     * Preferred language, e.g. for correspondence.
     *
     */
    public function getLanguageCode(): ?string
    {
        return $this->languageCode;
    }
    /**
     * Preferred language, e.g. for correspondence.
     *
     *
     * @return self
     */
    public function setLanguageCode(?string $languageCode): self
    {
        $this->initialized['languageCode'] = true;
        $this->languageCode = $languageCode;
        return $this;
    }
    /**
     * User's address.
     *
     */
    public function getAddress(): mixed
    {
        return $this->address;
    }
    /**
     * User's address.
     *
     *
     * @return self
     */
    public function setAddress(mixed $address): self
    {
        $this->initialized['address'] = true;
        $this->address = $address;
        return $this;
    }
    /**
     * Identity provider that governs this user or null for Picturepark's own IdentityServer.
     *
     */
    public function getIdentityProviderId(): ?string
    {
        return $this->identityProviderId;
    }
    /**
     * Identity provider that governs this user or null for Picturepark's own IdentityServer.
     *
     *
     * @return self
     */
    public function setIdentityProviderId(?string $identityProviderId): self
    {
        $this->initialized['identityProviderId'] = true;
        $this->identityProviderId = $identityProviderId;
        return $this;
    }
    /**
     * Owner tokens referencing the user.
     *
     * @return list<OwnerToken>|null
     */
    public function getOwnerTokens(): ?array
    {
        return $this->ownerTokens;
    }
    /**
     * Owner tokens referencing the user.
     *
     * @param list<OwnerToken>|null $ownerTokens
     *
     * @return self
     */
    public function setOwnerTokens(?array $ownerTokens): self
    {
        $this->initialized['ownerTokens'] = true;
        $this->ownerTokens = $ownerTokens;
        return $this;
    }
    /**
     * Authorization state the user is currently in.
     *
     */
    public function getAuthorizationState(): mixed
    {
        return $this->authorizationState;
    }
    /**
     * Authorization state the user is currently in.
     *
     *
     * @return self
     */
    public function setAuthorizationState(mixed $authorizationState): self
    {
        $this->initialized['authorizationState'] = true;
        $this->authorizationState = $authorizationState;
        return $this;
    }
    /**
     * Locked users are unable to log in and use the system.
     *
     */
    public function getIsLocked(): bool
    {
        return $this->isLocked;
    }
    /**
     * Locked users are unable to log in and use the system.
     *
     *
     * @return self
     */
    public function setIsLocked(bool $isLocked): self
    {
        $this->initialized['isLocked'] = true;
        $this->isLocked = $isLocked;
        return $this;
    }
    /**
     * Life cycle state the user is currently in.
     *
     */
    public function getLifeCycle(): mixed
    {
        return $this->lifeCycle;
    }
    /**
     * Life cycle state the user is currently in.
     *
     *
     * @return self
     */
    public function setLifeCycle(mixed $lifeCycle): self
    {
        $this->initialized['lifeCycle'] = true;
        $this->lifeCycle = $lifeCycle;
        return $this;
    }
    /**
     * The support user is a user created for Picturepark support personnel.
     *
     */
    public function getIsSupportUser(): bool
    {
        return $this->isSupportUser;
    }
    /**
     * The support user is a user created for Picturepark support personnel.
     *
     *
     * @return self
     */
    public function setIsSupportUser(bool $isSupportUser): self
    {
        $this->initialized['isSupportUser'] = true;
        $this->isSupportUser = $isSupportUser;
        return $this;
    }
    /**
     * Read-only users can't be removed from the system, e.g. service user.
     *
     */
    public function getIsReadOnly(): bool
    {
        return $this->isReadOnly;
    }
    /**
     * Read-only users can't be removed from the system, e.g. service user.
     *
     *
     * @return self
     */
    public function setIsReadOnly(bool $isReadOnly): self
    {
        $this->initialized['isReadOnly'] = true;
        $this->isReadOnly = $isReadOnly;
        return $this;
    }
    /**
     * Federated user is a user who is (currently) governed by an external identity provider.
     *
     */
    public function getIsFederated(): bool
    {
        return $this->isFederated;
    }
    /**
     * Federated user is a user who is (currently) governed by an external identity provider.
     *
     *
     * @return self
     */
    public function setIsFederated(bool $isFederated): self
    {
        $this->initialized['isFederated'] = true;
        $this->isFederated = $isFederated;
        return $this;
    }
    /**
     * Audit information.
     *
     */
    public function getAudit(): mixed
    {
        return $this->audit;
    }
    /**
     * Audit information.
     *
     *
     * @return self
     */
    public function setAudit(mixed $audit): self
    {
        $this->initialized['audit'] = true;
        $this->audit = $audit;
        return $this;
    }
}