<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ReferencedRequestBodies\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class _Parent extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $id;
    /**
     * @var list<Child>
     */
    protected array $child;
    public function getId(): string
    {
        return $this->id;
    }
    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;
        return $this;
    }
    /**
     * @return list<Child>
     */
    public function getChild(): array
    {
        return $this->child;
    }
    public function setChild(Child ...$child): self
    {
        $this->initialized['child'] = true;
        $this->child = array_values($child);
        return $this;
    }
}