<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator;

class OrgsOrgTeamsPostBodyConstraint extends \Symfony\Component\Validator\Constraints\Compound
{
    protected function getConstraints($options): array
    {
        return [new \Symfony\Component\Validator\Constraints\Collection(fields: ['name' => new \Symfony\Component\Validator\Constraints\Required([]), 'description' => new \Symfony\Component\Validator\Constraints\Optional([]), 'maintainers' => new \Symfony\Component\Validator\Constraints\Optional([]), 'repo_names' => new \Symfony\Component\Validator\Constraints\Optional([]), 'privacy' => new \Symfony\Component\Validator\Constraints\Optional([]), 'permission' => new \Symfony\Component\Validator\Constraints\Optional([]), 'parent_team_id' => new \Symfony\Component\Validator\Constraints\Optional([])], allowExtraFields: true)];
    }
}