<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator;

class ThreadConstraint extends \Symfony\Component\Validator\Constraints\Compound
{
    protected function getConstraints($options): array
    {
        return [new \Symfony\Component\Validator\Constraints\Collection(fields: ['id' => new \Symfony\Component\Validator\Constraints\Optional([]), 'repository' => new \Symfony\Component\Validator\Constraints\Optional([]), 'subject' => new \Symfony\Component\Validator\Constraints\Optional([]), 'reason' => new \Symfony\Component\Validator\Constraints\Optional([]), 'unread' => new \Symfony\Component\Validator\Constraints\Optional([]), 'updated_at' => new \Symfony\Component\Validator\Constraints\Optional([]), 'last_read_at' => new \Symfony\Component\Validator\Constraints\Optional([]), 'url' => new \Symfony\Component\Validator\Constraints\Optional([]), 'subscription_url' => new \Symfony\Component\Validator\Constraints\Optional([])], allowExtraFields: true)];
    }
}