<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator;

class WorkflowRunConstraint extends \Symfony\Component\Validator\Constraints\Compound
{
    protected function getConstraints($options): array
    {
        return [new \Symfony\Component\Validator\Constraints\Collection(fields: ['id' => new \Symfony\Component\Validator\Constraints\Required([]), 'node_id' => new \Symfony\Component\Validator\Constraints\Required([]), 'head_branch' => new \Symfony\Component\Validator\Constraints\Required([]), 'head_sha' => new \Symfony\Component\Validator\Constraints\Required([]), 'run_number' => new \Symfony\Component\Validator\Constraints\Required([]), 'event' => new \Symfony\Component\Validator\Constraints\Required([]), 'status' => new \Symfony\Component\Validator\Constraints\Required([]), 'conclusion' => new \Symfony\Component\Validator\Constraints\Required([]), 'workflow_id' => new \Symfony\Component\Validator\Constraints\Required([]), 'url' => new \Symfony\Component\Validator\Constraints\Required([]), 'html_url' => new \Symfony\Component\Validator\Constraints\Required([]), 'pull_requests' => new \Symfony\Component\Validator\Constraints\Required([]), 'created_at' => new \Symfony\Component\Validator\Constraints\Required([]), 'updated_at' => new \Symfony\Component\Validator\Constraints\Required([]), 'jobs_url' => new \Symfony\Component\Validator\Constraints\Required([]), 'logs_url' => new \Symfony\Component\Validator\Constraints\Required([]), 'check_suite_url' => new \Symfony\Component\Validator\Constraints\Required([]), 'artifacts_url' => new \Symfony\Component\Validator\Constraints\Required([]), 'cancel_url' => new \Symfony\Component\Validator\Constraints\Required([]), 'rerun_url' => new \Symfony\Component\Validator\Constraints\Required([]), 'workflow_url' => new \Symfony\Component\Validator\Constraints\Required([]), 'head_commit' => new \Symfony\Component\Validator\Constraints\Required([]), 'repository' => new \Symfony\Component\Validator\Constraints\Required([]), 'head_repository' => new \Symfony\Component\Validator\Constraints\Required([]), 'head_repository_id' => new \Symfony\Component\Validator\Constraints\Optional([])], allowExtraFields: true)];
    }
}