<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Twitter\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class RulesResponseMetadata extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $sent;
    /**
     * @var array<string, mixed>
     */
    protected array $summary;
    public function getSent(): string
    {
        return $this->sent;
    }
    public function setSent(string $sent): self
    {
        $this->initialized['sent'] = true;
        $this->sent = $sent;
        return $this;
    }
    /**
     * @return array<string, mixed>
     */
    public function getSummary(): array
    {
        return $this->summary;
    }
    /**
     * @param array<string, mixed> $summary
     *
     * @return self
     */
    public function setSummary(array $summary): self
    {
        $this->initialized['summary'] = true;
        $this->summary = $summary;
        return $this;
    }
}