<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class ListItemNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItem::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItem::class;
    }
    /**
     * @return \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItem|Reference
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItem|Reference
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItem();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (\array_key_exists('audit', $data) && $data['audit'] !== null) {
            $object->setAudit($data['audit']);
        }
        elseif (\array_key_exists('audit', $data) && $data['audit'] === null) {
            $object->setAudit(null);
        }
        if (\array_key_exists('id', $data)) {
            $object->setId(TypeValidator::assertString($data['id'], 'id'));
        }
        if (\array_key_exists('contentSchemaId', $data)) {
            $object->setContentSchemaId(TypeValidator::assertNullableString($data['contentSchemaId'], 'contentSchemaId'));
        }
        if (\array_key_exists('displayValues', $data) && $data['displayValues'] !== null) {
            $object->setDisplayValues($data['displayValues']);
        }
        elseif (\array_key_exists('displayValues', $data) && $data['displayValues'] === null) {
            $object->setDisplayValues(null);
        }
        if (\array_key_exists('content', $data) && $data['content'] !== null) {
            $values = [];
            if (\is_array($data['content'])) {
                foreach ($data['content'] as $key => $value) {
                    $values[(string) $key] = $value;
                }
            }
            $object->setContent($values);
        }
        elseif (\array_key_exists('content', $data) && $data['content'] === null) {
            $object->setContent(null);
        }
        if (\array_key_exists('brokenReferenceIds', $data) && $data['brokenReferenceIds'] !== null) {
            $values_1 = [];
            if (\is_array($data['brokenReferenceIds'])) {
                foreach ($data['brokenReferenceIds'] as $value_1) {
                    $values_1[] = TypeValidator::assertString($value_1, 'value');
                }
            }
            $object->setBrokenReferenceIds($values_1);
        }
        elseif (\array_key_exists('brokenReferenceIds', $data) && $data['brokenReferenceIds'] === null) {
            $object->setBrokenReferenceIds(null);
        }
        if (\array_key_exists('brokenRelationTargetIds', $data) && $data['brokenRelationTargetIds'] !== null) {
            $values_2 = [];
            if (\is_array($data['brokenRelationTargetIds'])) {
                foreach ($data['brokenRelationTargetIds'] as $value_2) {
                    $values_2[] = TypeValidator::assertString($value_2, 'value');
                }
            }
            $object->setBrokenRelationTargetIds($values_2);
        }
        elseif (\array_key_exists('brokenRelationTargetIds', $data) && $data['brokenRelationTargetIds'] === null) {
            $object->setBrokenRelationTargetIds(null);
        }
        if (\array_key_exists('brokenIndirectReferenceIds', $data) && $data['brokenIndirectReferenceIds'] !== null) {
            $values_3 = [];
            if (\is_array($data['brokenIndirectReferenceIds'])) {
                foreach ($data['brokenIndirectReferenceIds'] as $value_3) {
                    $values_3[] = TypeValidator::assertString($value_3, 'value');
                }
            }
            $object->setBrokenIndirectReferenceIds($values_3);
        }
        elseif (\array_key_exists('brokenIndirectReferenceIds', $data) && $data['brokenIndirectReferenceIds'] === null) {
            $object->setBrokenIndirectReferenceIds(null);
        }
        if (\array_key_exists('lifeCycle', $data)) {
            $object->setLifeCycle($data['lifeCycle']);
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItem) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItem, got ' . get_debug_type($data));
        }
        $dataArray = [];
        $val = $data->getAudit();
        if ($data->isInitialized('audit') && null !== $val) {
            $dataArray['audit'] = $val;
        }
        $dataArray['id'] = $data->getId();
        $val_1 = $data->getContentSchemaId();
        if ($data->isInitialized('contentSchemaId') && null !== $val_1) {
            $dataArray['contentSchemaId'] = $val_1;
        }
        $val_2 = $data->getDisplayValues();
        if ($data->isInitialized('displayValues') && null !== $val_2) {
            $dataArray['displayValues'] = $val_2;
        }
        $val_3 = $data->getContent();
        if ($data->isInitialized('content') && null !== $val_3) {
            $values = [];
            foreach ($val_3 as $key => $value) {
                $values[(string) $key] = $value;
            }
            $dataArray['content'] = $values;
        }
        $val_4 = $data->getBrokenReferenceIds();
        if ($data->isInitialized('brokenReferenceIds') && null !== $val_4) {
            $values_1 = [];
            foreach ($val_4 as $value_1) {
                $values_1[] = $value_1;
            }
            $dataArray['brokenReferenceIds'] = $values_1;
        }
        $val_5 = $data->getBrokenRelationTargetIds();
        if ($data->isInitialized('brokenRelationTargetIds') && null !== $val_5) {
            $values_2 = [];
            foreach ($val_5 as $value_2) {
                $values_2[] = $value_2;
            }
            $dataArray['brokenRelationTargetIds'] = $values_2;
        }
        $val_6 = $data->getBrokenIndirectReferenceIds();
        if ($data->isInitialized('brokenIndirectReferenceIds') && null !== $val_6) {
            $values_3 = [];
            foreach ($val_6 as $value_3) {
                $values_3[] = $value_3;
            }
            $dataArray['brokenIndirectReferenceIds'] = $values_3;
        }
        $dataArray['lifeCycle'] = $data->getLifeCycle();
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItem::class => false];
    }
}