<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class ListItemFieldsBatchUpdateRequestNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItemFieldsBatchUpdateRequest::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && $data::class === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItemFieldsBatchUpdateRequest::class;
    }
    /**
     * The denormalized result is either a \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItemFieldsBatchUpdateRequest or a Reference.
     * Native return type is `mixed` for Symfony interface covariance — callers
     * must narrow via TypeValidator::assertInstanceOf.
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItemFieldsBatchUpdateRequest();
        if (!\is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (\array_key_exists('listItemIds', $data)) {
            $values = [];
            if (\is_array($data['listItemIds'])) {
                foreach ($data['listItemIds'] as $value) {
                    $values[] = TypeValidator::assertString($value, 'value');
                }
            }
            $object->setListItemIds($values);
        }
        if (\array_key_exists('changeCommands', $data)) {
            $values_1 = [];
            if (\is_array($data['changeCommands'])) {
                foreach ($data['changeCommands'] as $value_1) {
                    $value_2 = TypeValidator::assertInstanceOf($this->denormalizer->denormalize($value_1, \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\MetadataValuesChangeCommandBase::class, 'json', $context), \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\MetadataValuesChangeCommandBase::class, 'MetadataValuesChangeCommandBase');
                    $values_1[] = $value_2;
                }
            }
            $object->setChangeCommands($values_1);
        }
        if (\array_key_exists('allowMissingDependencies', $data)) {
            $object->setAllowMissingDependencies(TypeValidator::assertBool($data['allowMissingDependencies'], 'allowMissingDependencies'));
        }
        if (\array_key_exists('notifyProgress', $data)) {
            $object->setNotifyProgress(TypeValidator::assertBool($data['notifyProgress'], 'notifyProgress'));
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItemFieldsBatchUpdateRequest) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItemFieldsBatchUpdateRequest, got ' . get_debug_type($data));
        }
        $dataArray = [];
        $values = [];
        foreach ($data->getListItemIds() as $value) {
            $values[] = $value;
        }
        $dataArray['listItemIds'] = $values;
        $values_1 = [];
        foreach ($data->getChangeCommands() as $value_1) {
            $values_1[] = $this->normalizer->normalize($value_1, 'json', $context);
        }
        $dataArray['changeCommands'] = $values_1;
        $dataArray['allowMissingDependencies'] = $data->getAllowMissingDependencies();
        $dataArray['notifyProgress'] = $data->getNotifyProgress();
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue445\Model\ListItemFieldsBatchUpdateRequest::class => false];
    }
}