<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class BaseGistNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGist::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGist::class;
    }
    /**
     * @return \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGist|Reference
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGist|Reference
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGist();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (!(bool) ($context['skip_validation'] ?? false)) {
            $this->validate($data, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\BaseGistConstraint());
        }
        if (\array_key_exists('url', $data)) {
            $object->setUrl(TypeValidator::assertString($data['url'], 'url'));
            unset($data['url']);
        }
        if (\array_key_exists('forks_url', $data)) {
            $object->setForksUrl(TypeValidator::assertString($data['forks_url'], 'forks_url'));
            unset($data['forks_url']);
        }
        if (\array_key_exists('commits_url', $data)) {
            $object->setCommitsUrl(TypeValidator::assertString($data['commits_url'], 'commits_url'));
            unset($data['commits_url']);
        }
        if (\array_key_exists('id', $data)) {
            $object->setId(TypeValidator::assertString($data['id'], 'id'));
            unset($data['id']);
        }
        if (\array_key_exists('node_id', $data)) {
            $object->setNodeId(TypeValidator::assertString($data['node_id'], 'node_id'));
            unset($data['node_id']);
        }
        if (\array_key_exists('git_pull_url', $data)) {
            $object->setGitPullUrl(TypeValidator::assertString($data['git_pull_url'], 'git_pull_url'));
            unset($data['git_pull_url']);
        }
        if (\array_key_exists('git_push_url', $data)) {
            $object->setGitPushUrl(TypeValidator::assertString($data['git_push_url'], 'git_push_url'));
            unset($data['git_push_url']);
        }
        if (\array_key_exists('html_url', $data)) {
            $object->setHtmlUrl(TypeValidator::assertString($data['html_url'], 'html_url'));
            unset($data['html_url']);
        }
        if (\array_key_exists('files', $data)) {
            $values = [];
            if (\is_array($data['files'])) {
                foreach ($data['files'] as $key => $value) {
                    $value_1 = $this->denormalizer->denormalize($value, \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGistFilesItem::class, 'json', $context);
                    if (!$value_1 instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGistFilesItem) {
                        throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGistFilesItem, got ' . get_debug_type($value_1));
                    }
                    $values[(string) $key] = $value_1;
                }
            }
            $object->setFiles($values);
            unset($data['files']);
        }
        if (\array_key_exists('public', $data)) {
            $object->setPublic(TypeValidator::assertBool($data['public'], 'public'));
            unset($data['public']);
        }
        if (\array_key_exists('created_at', $data)) {
            $object->setCreatedAt(TypeValidator::assertDateTime($data['created_at'], 'Y-m-d\TH:i:sP', 'datetime'));
            unset($data['created_at']);
        }
        if (\array_key_exists('updated_at', $data)) {
            $object->setUpdatedAt(TypeValidator::assertDateTime($data['updated_at'], 'Y-m-d\TH:i:sP', 'datetime'));
            unset($data['updated_at']);
        }
        if (\array_key_exists('description', $data)) {
            $object->setDescription(TypeValidator::assertNullableString($data['description'], 'description'));
            unset($data['description']);
        }
        if (\array_key_exists('comments', $data)) {
            $object->setComments(TypeValidator::assertInt($data['comments'], 'comments'));
            unset($data['comments']);
        }
        if (\array_key_exists('user', $data) && $data['user'] !== null) {
            $value_2 = $this->denormalizer->denormalize($data['user'], \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGistUser::class, 'json', $context);
            if (!$value_2 instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGistUser) {
                throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGistUser, got ' . get_debug_type($value_2));
            }
            $object->setUser($value_2);
            unset($data['user']);
        }
        elseif (\array_key_exists('user', $data) && $data['user'] === null) {
            $object->setUser(null);
        }
        if (\array_key_exists('comments_url', $data)) {
            $object->setCommentsUrl(TypeValidator::assertString($data['comments_url'], 'comments_url'));
            unset($data['comments_url']);
        }
        if (\array_key_exists('owner', $data) && $data['owner'] !== null) {
            $value_3 = $this->denormalizer->denormalize($data['owner'], \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGistOwner::class, 'json', $context);
            if (!$value_3 instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGistOwner) {
                throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGistOwner, got ' . get_debug_type($value_3));
            }
            $object->setOwner($value_3);
            unset($data['owner']);
        }
        elseif (\array_key_exists('owner', $data) && $data['owner'] === null) {
            $object->setOwner(null);
        }
        if (\array_key_exists('truncated', $data)) {
            $object->setTruncated(TypeValidator::assertBool($data['truncated'], 'truncated'));
            unset($data['truncated']);
        }
        if (\array_key_exists('forks', $data)) {
            $values_1 = [];
            if (\is_array($data['forks'])) {
                foreach ($data['forks'] as $value_4) {
                    $values_1[] = $value_4;
                }
            }
            $object->setForks($values_1);
            unset($data['forks']);
        }
        if (\array_key_exists('history', $data)) {
            $values_2 = [];
            if (\is_array($data['history'])) {
                foreach ($data['history'] as $value_5) {
                    $values_2[] = $value_5;
                }
            }
            $object->setHistory($values_2);
            unset($data['history']);
        }
        foreach ($data as $key_1 => $value_6) {
            if (preg_match('/.*/', (string) $key_1) === 1) {
                $object[$key_1] = $value_6;
            }
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGist) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGist, got ' . get_debug_type($data));
        }
        $dataArray = [];
        $dataArray['url'] = $data->getUrl();
        $dataArray['forks_url'] = $data->getForksUrl();
        $dataArray['commits_url'] = $data->getCommitsUrl();
        $dataArray['id'] = $data->getId();
        $dataArray['node_id'] = $data->getNodeId();
        $dataArray['git_pull_url'] = $data->getGitPullUrl();
        $dataArray['git_push_url'] = $data->getGitPushUrl();
        $dataArray['html_url'] = $data->getHtmlUrl();
        $values = [];
        foreach ($data->getFiles() as $key => $value) {
            $values[(string) $key] = $this->normalizer->normalize($value, 'json', $context);
        }
        $dataArray['files'] = $values;
        $dataArray['public'] = $data->getPublic();
        $dataArray['created_at'] = $data->getCreatedAt()->format('Y-m-d\TH:i:sP');
        $dataArray['updated_at'] = $data->getUpdatedAt()->format('Y-m-d\TH:i:sP');
        $val = $data->getDescription();
        if (null !== $val) {
            $dataArray['description'] = $val;
        } else {
            $dataArray['description'] = null;
        }
        $dataArray['comments'] = $data->getComments();
        $val_1 = $data->getUser();
        if (null !== $val_1) {
            $dataArray['user'] = $this->normalizer->normalize($val_1, 'json', $context);
        } else {
            $dataArray['user'] = null;
        }
        $dataArray['comments_url'] = $data->getCommentsUrl();
        $val_2 = $data->getOwner();
        if ($data->isInitialized('owner') && null !== $val_2) {
            $dataArray['owner'] = $this->normalizer->normalize($val_2, 'json', $context);
        }
        if ($data->isInitialized('truncated')) {
            $dataArray['truncated'] = $data->getTruncated();
        }
        if ($data->isInitialized('forks')) {
            $values_1 = [];
            foreach ($data->getForks() as $value_1) {
                $values_1[] = $value_1;
            }
            $dataArray['forks'] = $values_1;
        }
        if ($data->isInitialized('history')) {
            $values_2 = [];
            foreach ($data->getHistory() as $value_2) {
                $values_2[] = $value_2;
            }
            $dataArray['history'] = $values_2;
        }
        foreach ($data as $key_1 => $value_3) {
            if (preg_match('/.*/', (string) $key_1) === 1) {
                $dataArray[(string) $key_1] = $value_3;
            }
        }
        if (!(bool) ($context['skip_validation'] ?? false)) {
            $this->validate($dataArray, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\BaseGistConstraint());
        }
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\BaseGist::class => false];
    }
}