<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class JobNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Job::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Job::class;
    }
    /**
     * The denormalized result is either a \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Job or a Reference.
     * Native return type is `mixed` for Symfony interface covariance — callers
     * must narrow via TypeValidator::assertInstanceOf.
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Job();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (!(bool) ($context['skip_validation'] ?? false)) {
            $this->validate($data, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\JobConstraint());
        }
        if (\array_key_exists('id', $data)) {
            $object->setId(TypeValidator::assertInt($data['id'], 'id'));
            unset($data['id']);
        }
        if (\array_key_exists('run_id', $data)) {
            $object->setRunId(TypeValidator::assertInt($data['run_id'], 'run_id'));
            unset($data['run_id']);
        }
        if (\array_key_exists('run_url', $data)) {
            $object->setRunUrl(TypeValidator::assertString($data['run_url'], 'run_url'));
            unset($data['run_url']);
        }
        if (\array_key_exists('node_id', $data)) {
            $object->setNodeId(TypeValidator::assertString($data['node_id'], 'node_id'));
            unset($data['node_id']);
        }
        if (\array_key_exists('head_sha', $data)) {
            $object->setHeadSha(TypeValidator::assertString($data['head_sha'], 'head_sha'));
            unset($data['head_sha']);
        }
        if (\array_key_exists('url', $data)) {
            $object->setUrl(TypeValidator::assertString($data['url'], 'url'));
            unset($data['url']);
        }
        if (\array_key_exists('html_url', $data)) {
            $object->setHtmlUrl(TypeValidator::assertNullableString($data['html_url'], 'html_url'));
            unset($data['html_url']);
        }
        if (\array_key_exists('status', $data)) {
            $object->setStatus(TypeValidator::assertString($data['status'], 'status'));
            unset($data['status']);
        }
        if (\array_key_exists('conclusion', $data)) {
            $object->setConclusion(TypeValidator::assertNullableString($data['conclusion'], 'conclusion'));
            unset($data['conclusion']);
        }
        if (\array_key_exists('started_at', $data)) {
            $object->setStartedAt(TypeValidator::assertDateTime($data['started_at'], 'Y-m-d\TH:i:sP', 'datetime'));
            unset($data['started_at']);
        }
        if (\array_key_exists('completed_at', $data) && $data['completed_at'] !== null) {
            $object->setCompletedAt(TypeValidator::assertDateTime($data['completed_at'], 'Y-m-d\TH:i:sP', 'datetime'));
            unset($data['completed_at']);
        }
        elseif (\array_key_exists('completed_at', $data) && $data['completed_at'] === null) {
            $object->setCompletedAt(null);
        }
        if (\array_key_exists('name', $data)) {
            $object->setName(TypeValidator::assertString($data['name'], 'name'));
            unset($data['name']);
        }
        if (\array_key_exists('steps', $data)) {
            $values = [];
            if (\is_array($data['steps'])) {
                foreach ($data['steps'] as $value) {
                    $value_1 = TypeValidator::assertInstanceOf($this->denormalizer->denormalize($value, \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\JobStepsItem::class, 'json', $context), \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\JobStepsItem::class, 'JobStepsItem');
                    $values[] = $value_1;
                }
            }
            $object->setSteps($values);
            unset($data['steps']);
        }
        if (\array_key_exists('check_run_url', $data)) {
            $object->setCheckRunUrl(TypeValidator::assertString($data['check_run_url'], 'check_run_url'));
            unset($data['check_run_url']);
        }
        foreach ($data as $key => $value_2) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $object[$key] = $value_2;
            }
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Job) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Job, got ' . get_debug_type($data));
        }
        $dataArray = [];
        $dataArray['id'] = $data->getId();
        $dataArray['run_id'] = $data->getRunId();
        $dataArray['run_url'] = $data->getRunUrl();
        $dataArray['node_id'] = $data->getNodeId();
        $dataArray['head_sha'] = $data->getHeadSha();
        $dataArray['url'] = $data->getUrl();
        $val = $data->getHtmlUrl();
        if (null !== $val) {
            $dataArray['html_url'] = $val;
        } else {
            $dataArray['html_url'] = null;
        }
        $dataArray['status'] = $data->getStatus();
        $val_1 = $data->getConclusion();
        if (null !== $val_1) {
            $dataArray['conclusion'] = $val_1;
        } else {
            $dataArray['conclusion'] = null;
        }
        $dataArray['started_at'] = $data->getStartedAt()->format('Y-m-d\TH:i:sP');
        $val_2 = $data->getCompletedAt();
        if (null !== $val_2) {
            $dataArray['completed_at'] = $val_2->format('Y-m-d\TH:i:sP');
        } else {
            $dataArray['completed_at'] = null;
        }
        $dataArray['name'] = $data->getName();
        if ($data->isInitialized('steps')) {
            $values = [];
            foreach ($data->getSteps() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $dataArray['steps'] = $values;
        }
        $dataArray['check_run_url'] = $data->getCheckRunUrl();
        foreach ($data as $key => $value_1) {
            if (preg_match('/.*/', strval($key)) === 1) {
                $dataArray[$key] = $value_1;
            }
        }
        if (!(bool) ($context['skip_validation'] ?? false)) {
            $this->validate($dataArray, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\JobConstraint());
        }
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Job::class => false];
    }
}