<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class PackagesBillingUsageNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\PackagesBillingUsage::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && $data::class === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\PackagesBillingUsage::class;
    }
    /**
     * The denormalized result is either a \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\PackagesBillingUsage or a Reference.
     * Native return type is `mixed` for Symfony interface covariance — callers
     * must narrow via TypeValidator::assertInstanceOf.
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\PackagesBillingUsage();
        if (!\is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (true !== ($context['skip_validation'] ?? null)) {
            $this->validate($data, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\PackagesBillingUsageConstraint());
        }
        if (\array_key_exists('total_gigabytes_bandwidth_used', $data)) {
            $object->setTotalGigabytesBandwidthUsed(TypeValidator::assertInt($data['total_gigabytes_bandwidth_used'], 'total_gigabytes_bandwidth_used'));
            unset($data['total_gigabytes_bandwidth_used']);
        }
        if (\array_key_exists('total_paid_gigabytes_bandwidth_used', $data)) {
            $object->setTotalPaidGigabytesBandwidthUsed(TypeValidator::assertInt($data['total_paid_gigabytes_bandwidth_used'], 'total_paid_gigabytes_bandwidth_used'));
            unset($data['total_paid_gigabytes_bandwidth_used']);
        }
        if (\array_key_exists('included_gigabytes_bandwidth', $data)) {
            $object->setIncludedGigabytesBandwidth(TypeValidator::assertInt($data['included_gigabytes_bandwidth'], 'included_gigabytes_bandwidth'));
            unset($data['included_gigabytes_bandwidth']);
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $object[$key] = $value;
            }
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\PackagesBillingUsage) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\PackagesBillingUsage, got ' . get_debug_type($data));
        }
        $dataArray = [];
        if ($data->isInitialized('totalGigabytesBandwidthUsed')) {
            $dataArray['total_gigabytes_bandwidth_used'] = $data->getTotalGigabytesBandwidthUsed();
        }
        if ($data->isInitialized('totalPaidGigabytesBandwidthUsed')) {
            $dataArray['total_paid_gigabytes_bandwidth_used'] = $data->getTotalPaidGigabytesBandwidthUsed();
        }
        if ($data->isInitialized('includedGigabytesBandwidth')) {
            $dataArray['included_gigabytes_bandwidth'] = $data->getIncludedGigabytesBandwidth();
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', strval($key)) === 1) {
                $dataArray[$key] = $value;
            }
        }
        if (true !== ($context['skip_validation'] ?? null)) {
            $this->validate($dataArray, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\PackagesBillingUsageConstraint());
        }
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\PackagesBillingUsage::class => false];
    }
}