<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class ReleaseAssetNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReleaseAsset::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && $data::class === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReleaseAsset::class;
    }
    /**
     * The denormalized result is either a \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReleaseAsset or a Reference.
     * Native return type is `mixed` for Symfony interface covariance — callers
     * must narrow via TypeValidator::assertInstanceOf.
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReleaseAsset();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (!(bool) ($context['skip_validation'] ?? false)) {
            $this->validate($data, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\ReleaseAssetConstraint());
        }
        if (\array_key_exists('url', $data)) {
            $object->setUrl(TypeValidator::assertString($data['url'], 'url'));
            unset($data['url']);
        }
        if (\array_key_exists('browser_download_url', $data)) {
            $object->setBrowserDownloadUrl(TypeValidator::assertString($data['browser_download_url'], 'browser_download_url'));
            unset($data['browser_download_url']);
        }
        if (\array_key_exists('id', $data)) {
            $object->setId(TypeValidator::assertInt($data['id'], 'id'));
            unset($data['id']);
        }
        if (\array_key_exists('node_id', $data)) {
            $object->setNodeId(TypeValidator::assertString($data['node_id'], 'node_id'));
            unset($data['node_id']);
        }
        if (\array_key_exists('name', $data)) {
            $object->setName(TypeValidator::assertString($data['name'], 'name'));
            unset($data['name']);
        }
        if (\array_key_exists('label', $data)) {
            $object->setLabel(TypeValidator::assertNullableString($data['label'], 'label'));
            unset($data['label']);
        }
        if (\array_key_exists('state', $data)) {
            $object->setState(TypeValidator::assertString($data['state'], 'state'));
            unset($data['state']);
        }
        if (\array_key_exists('content_type', $data)) {
            $object->setContentType(TypeValidator::assertString($data['content_type'], 'content_type'));
            unset($data['content_type']);
        }
        if (\array_key_exists('size', $data)) {
            $object->setSize(TypeValidator::assertInt($data['size'], 'size'));
            unset($data['size']);
        }
        if (\array_key_exists('download_count', $data)) {
            $object->setDownloadCount(TypeValidator::assertInt($data['download_count'], 'download_count'));
            unset($data['download_count']);
        }
        if (\array_key_exists('created_at', $data)) {
            $object->setCreatedAt(TypeValidator::assertDateTime($data['created_at'], 'Y-m-d\TH:i:sP', 'datetime'));
            unset($data['created_at']);
        }
        if (\array_key_exists('updated_at', $data)) {
            $object->setUpdatedAt(TypeValidator::assertDateTime($data['updated_at'], 'Y-m-d\TH:i:sP', 'datetime'));
            unset($data['updated_at']);
        }
        if (\array_key_exists('uploader', $data) && $data['uploader'] !== null) {
            $value = TypeValidator::assertInstanceOf($this->denormalizer->denormalize($data['uploader'], \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReleaseAssetUploader::class, 'json', $context), \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReleaseAssetUploader::class, 'ReleaseAssetUploader');
            $object->setUploader($value);
            unset($data['uploader']);
        }
        elseif (\array_key_exists('uploader', $data) && $data['uploader'] === null) {
            $object->setUploader(null);
        }
        foreach ($data as $key => $value_1) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $object[$key] = $value_1;
            }
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReleaseAsset) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReleaseAsset, got ' . get_debug_type($data));
        }
        $dataArray = [];
        $dataArray['url'] = $data->getUrl();
        $dataArray['browser_download_url'] = $data->getBrowserDownloadUrl();
        $dataArray['id'] = $data->getId();
        $dataArray['node_id'] = $data->getNodeId();
        $dataArray['name'] = $data->getName();
        $val = $data->getLabel();
        if (null !== $val) {
            $dataArray['label'] = $val;
        } else {
            $dataArray['label'] = null;
        }
        $dataArray['state'] = $data->getState();
        $dataArray['content_type'] = $data->getContentType();
        $dataArray['size'] = $data->getSize();
        $dataArray['download_count'] = $data->getDownloadCount();
        $dataArray['created_at'] = $data->getCreatedAt()->format('Y-m-d\TH:i:sP');
        $dataArray['updated_at'] = $data->getUpdatedAt()->format('Y-m-d\TH:i:sP');
        $val_1 = $data->getUploader();
        if (null !== $val_1) {
            $dataArray['uploader'] = $this->normalizer->normalize($val_1, 'json', $context);
        } else {
            $dataArray['uploader'] = null;
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', strval($key)) === 1) {
                $dataArray[$key] = $value;
            }
        }
        if (!(bool) ($context['skip_validation'] ?? false)) {
            $this->validate($dataArray, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\ReleaseAssetConstraint());
        }
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReleaseAsset::class => false];
    }
}