<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class RepositorySubscriptionNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\RepositorySubscription::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\RepositorySubscription::class;
    }
    /**
     * @return \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\RepositorySubscription|Reference
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\RepositorySubscription|Reference
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\RepositorySubscription();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (!(bool) ($context['skip_validation'] ?? false)) {
            $this->validate($data, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\RepositorySubscriptionConstraint());
        }
        if (\array_key_exists('subscribed', $data)) {
            $object->setSubscribed(TypeValidator::assertBool($data['subscribed'], 'subscribed'));
            unset($data['subscribed']);
        }
        if (\array_key_exists('ignored', $data)) {
            $object->setIgnored(TypeValidator::assertBool($data['ignored'], 'ignored'));
            unset($data['ignored']);
        }
        if (\array_key_exists('reason', $data)) {
            $object->setReason(TypeValidator::assertNullableString($data['reason'], 'reason'));
            unset($data['reason']);
        }
        if (\array_key_exists('created_at', $data)) {
            $object->setCreatedAt(TypeValidator::assertDateTime($data['created_at'], 'Y-m-d\TH:i:sP', 'datetime'));
            unset($data['created_at']);
        }
        if (\array_key_exists('url', $data)) {
            $object->setUrl(TypeValidator::assertString($data['url'], 'url'));
            unset($data['url']);
        }
        if (\array_key_exists('repository_url', $data)) {
            $object->setRepositoryUrl(TypeValidator::assertString($data['repository_url'], 'repository_url'));
            unset($data['repository_url']);
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $object[$key] = $value;
            }
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\RepositorySubscription) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\RepositorySubscription, got ' . get_debug_type($data));
        }
        $dataArray = [];
        $dataArray['subscribed'] = $data->getSubscribed();
        $dataArray['ignored'] = $data->getIgnored();
        $val = $data->getReason();
        if (null !== $val) {
            $dataArray['reason'] = $val;
        } else {
            $dataArray['reason'] = null;
        }
        $dataArray['created_at'] = $data->getCreatedAt()->format('Y-m-d\TH:i:sP');
        $dataArray['url'] = $data->getUrl();
        $dataArray['repository_url'] = $data->getRepositoryUrl();
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $dataArray[(string) $key] = $value;
            }
        }
        if (!(bool) ($context['skip_validation'] ?? false)) {
            $this->validate($dataArray, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\RepositorySubscriptionConstraint());
        }
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\RepositorySubscription::class => false];
    }
}