<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class ReviewCommentLinksNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReviewCommentLinks::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReviewCommentLinks::class;
    }
    /**
     * The denormalized result is either a \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReviewCommentLinks or a Reference.
     * Native return type is `mixed` for Symfony interface covariance — callers
     * must narrow via TypeValidator::assertInstanceOf.
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReviewCommentLinks();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (!(bool) ($context['skip_validation'] ?? false)) {
            $this->validate($data, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\ReviewCommentLinksConstraint());
        }
        if (\array_key_exists('self', $data)) {
            $value = $this->denormalizer->denormalize($data['self'], \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Link::class, 'json', $context);
            if (!$value instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Link) {
                throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Link, got ' . get_debug_type($value));
            }
            $object->setSelf($value);
            unset($data['self']);
        }
        if (\array_key_exists('html', $data)) {
            $value_1 = $this->denormalizer->denormalize($data['html'], \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Link::class, 'json', $context);
            if (!$value_1 instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Link) {
                throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Link, got ' . get_debug_type($value_1));
            }
            $object->setHtml($value_1);
            unset($data['html']);
        }
        if (\array_key_exists('pull_request', $data)) {
            $value_2 = $this->denormalizer->denormalize($data['pull_request'], \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Link::class, 'json', $context);
            if (!$value_2 instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Link) {
                throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\Link, got ' . get_debug_type($value_2));
            }
            $object->setPullRequest($value_2);
            unset($data['pull_request']);
        }
        foreach ($data as $key => $value_3) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $object[$key] = $value_3;
            }
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReviewCommentLinks) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReviewCommentLinks, got ' . get_debug_type($data));
        }
        $dataArray = [];
        $dataArray['self'] = $this->normalizer->normalize($data->getSelf(), 'json', $context);
        $dataArray['html'] = $this->normalizer->normalize($data->getHtml(), 'json', $context);
        $dataArray['pull_request'] = $this->normalizer->normalize($data->getPullRequest(), 'json', $context);
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $dataArray[(string) $key] = $value;
            }
        }
        if (!(bool) ($context['skip_validation'] ?? false)) {
            $this->validate($dataArray, new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Validator\ReviewCommentLinksConstraint());
        }
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Github\Model\ReviewCommentLinks::class => false];
    }
}