<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Normalizer;

use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Runtime\Normalizer\Reference;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Runtime\Normalizer\CheckArray;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Runtime\Normalizer\ValidatorTrait;
use LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Runtime\Normalizer\TypeValidator;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class ReviewReviewReadNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Model\ReviewReviewRead::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && $data::class === \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Model\ReviewReviewRead::class;
    }
    /**
     * The denormalized result is either a \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Model\ReviewReviewRead or a Reference.
     * Native return type is `mixed` for Symfony interface covariance — callers
     * must narrow via TypeValidator::assertInstanceOf.
     */
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Model\ReviewReviewRead();
        if (!\is_array($data)) {
            return $object;
        }
        if (isset($data['$ref'])) {
            return new Reference(TypeValidator::assertString($data['$ref'], '$ref'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference(TypeValidator::assertString($data['$recursiveRef'], '$recursiveRef'), TypeValidator::assertString($context['document-origin'], 'context.document-origin'));
        }
        if (\array_key_exists('id', $data)) {
            $object->setId(TypeValidator::assertNullableString($data['id'], 'id'));
            unset($data['id']);
        }
        if (\array_key_exists('body', $data)) {
            $object->setBody(TypeValidator::assertString($data['body'], 'body'));
            unset($data['body']);
        }
        if (\array_key_exists('rating', $data)) {
            $object->setRating(TypeValidator::assertInt($data['rating'], 'rating'));
            unset($data['rating']);
        }
        if (\array_key_exists('letter', $data)) {
            $object->setLetter(TypeValidator::assertNullableString($data['letter'], 'letter'));
            unset($data['letter']);
        }
        if (\array_key_exists('book', $data)) {
            $value = TypeValidator::assertInstanceOf($this->denormalizer->denormalize($data['book'], \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Model\BookReviewRead::class, 'json', $context), \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Model\BookReviewRead::class, 'BookReviewRead');
            $object->setBook($value);
            unset($data['book']);
        }
        if (\array_key_exists('author', $data)) {
            $object->setAuthor(TypeValidator::assertNullableString($data['author'], 'author'));
            unset($data['author']);
        }
        if (\array_key_exists('publicationDate', $data) && $data['publicationDate'] !== null) {
            $object->setPublicationDate(TypeValidator::assertDateTime($data['publicationDate'], 'Y-m-d\TH:i:sP', 'datetime'));
            unset($data['publicationDate']);
        }
        elseif (\array_key_exists('publicationDate', $data) && $data['publicationDate'] === null) {
            $object->setPublicationDate(null);
        }
        foreach ($data as $key => $value_1) {
            if (preg_match('/.*/', (string) $key) === 1) {
                $object[$key] = $value_1;
            }
        }
        return $object;
    }
    /**
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     * @phpstan-return array<int|string, mixed>|string|int|float|bool|\ArrayObject<int|string, mixed>|null
     */
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        if (!$data instanceof \LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Model\ReviewReviewRead) {
            throw new \LogicException('Expected LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Model\ReviewReviewRead, got ' . get_debug_type($data));
        }
        $dataArray = [];
        $dataArray['body'] = $data->getBody();
        $dataArray['rating'] = $data->getRating();
        $val = $data->getLetter();
        if ($data->isInitialized('letter') && null !== $val) {
            $dataArray['letter'] = $val;
        }
        $dataArray['book'] = $this->normalizer->normalize($data->getBook(), 'json', $context);
        $val_1 = $data->getAuthor();
        if ($data->isInitialized('author') && null !== $val_1) {
            $dataArray['author'] = $val_1;
        }
        $val_2 = $data->getPublicationDate();
        if ($data->isInitialized('publicationDate') && null !== $val_2) {
            $dataArray['publicationDate'] = $val_2->format('Y-m-d\TH:i:sP');
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', strval($key)) === 1) {
                $dataArray[$key] = $value;
            }
        }
        return $dataArray;
    }
    /**
     * @return array<class-string, bool>
     */
    public function getSupportedTypes(?string $format = null): array
    {
        return [\LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\ApiPlatformDemo\Model\ReviewReviewRead::class => false];
    }
}