<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class CompletedFreshInvestigation extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $chargeReference;
    protected CompletedFreshInvestigationContactDetails $contactDetails;
    protected string $creationDate;
    protected string $lastStatusChangeDate;
    protected int $orderID;
    protected string $reportDate;
    protected CompletedFreshInvestigationSearchCriteria $searchCriteria;
    /**
     * @var list<mixed>
     */
    protected array $sections;
    protected CompletedFreshInvestigationStatus $status;
    protected int $transactionID;
    public function getChargeReference(): string
    {
        return $this->chargeReference;
    }
    public function setChargeReference(string $chargeReference): self
    {
        $this->initialized['chargeReference'] = true;
        $this->chargeReference = $chargeReference;
        return $this;
    }
    public function getContactDetails(): CompletedFreshInvestigationContactDetails
    {
        return $this->contactDetails;
    }
    public function setContactDetails(CompletedFreshInvestigationContactDetails $contactDetails): self
    {
        $this->initialized['contactDetails'] = true;
        $this->contactDetails = $contactDetails;
        return $this;
    }
    public function getCreationDate(): string
    {
        return $this->creationDate;
    }
    public function setCreationDate(string $creationDate): self
    {
        $this->initialized['creationDate'] = true;
        $this->creationDate = $creationDate;
        return $this;
    }
    public function getLastStatusChangeDate(): string
    {
        return $this->lastStatusChangeDate;
    }
    public function setLastStatusChangeDate(string $lastStatusChangeDate): self
    {
        $this->initialized['lastStatusChangeDate'] = true;
        $this->lastStatusChangeDate = $lastStatusChangeDate;
        return $this;
    }
    public function getOrderID(): int
    {
        return $this->orderID;
    }
    public function setOrderID(int $orderID): self
    {
        $this->initialized['orderID'] = true;
        $this->orderID = $orderID;
        return $this;
    }
    public function getReportDate(): string
    {
        return $this->reportDate;
    }
    public function setReportDate(string $reportDate): self
    {
        $this->initialized['reportDate'] = true;
        $this->reportDate = $reportDate;
        return $this;
    }
    public function getSearchCriteria(): CompletedFreshInvestigationSearchCriteria
    {
        return $this->searchCriteria;
    }
    public function setSearchCriteria(CompletedFreshInvestigationSearchCriteria $searchCriteria): self
    {
        $this->initialized['searchCriteria'] = true;
        $this->searchCriteria = $searchCriteria;
        return $this;
    }
    /**
     * @return list<mixed>
     */
    public function getSections(): array
    {
        return $this->sections;
    }
    /**
     * @param list<mixed> $sections
     */
    public function setSections(array $sections): self
    {
        $this->initialized['sections'] = true;
        $this->sections = $sections;
        return $this;
    }
    public function getStatus(): CompletedFreshInvestigationStatus
    {
        return $this->status;
    }
    public function setStatus(CompletedFreshInvestigationStatus $status): self
    {
        $this->initialized['status'] = true;
        $this->status = $status;
        return $this;
    }
    public function getTransactionID(): int
    {
        return $this->transactionID;
    }
    public function setTransactionID(int $transactionID): self
    {
        $this->initialized['transactionID'] = true;
        $this->transactionID = $transactionID;
        return $this;
    }
}