<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class GbCompanyReportExampleResponseReportNegativeInformationCcjSummary extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected float $exactRegistered;
    protected float $possibleRegistered;
    public function getExactRegistered(): float
    {
        return $this->exactRegistered;
    }
    public function setExactRegistered(float $exactRegistered): self
    {
        $this->initialized['exactRegistered'] = true;
        $this->exactRegistered = $exactRegistered;
        return $this;
    }
    public function getPossibleRegistered(): float
    {
        return $this->possibleRegistered;
    }
    public function setPossibleRegistered(float $possibleRegistered): self
    {
        $this->initialized['possibleRegistered'] = true;
        $this->possibleRegistered = $possibleRegistered;
        return $this;
    }
}