<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class GbCompanyReportExampleResponseReportAdditionalInformationBadDebtDetailsItem extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $statementDate;
    protected string $registrationNumber;
    protected string $companyName;
    protected GbCompanyReportExampleResponseReportAdditionalInformationBadDebtDetailsItemAmount $amount;
    public function getStatementDate(): string
    {
        return $this->statementDate;
    }
    public function setStatementDate(string $statementDate): self
    {
        $this->initialized['statementDate'] = true;
        $this->statementDate = $statementDate;
        return $this;
    }
    public function getRegistrationNumber(): string
    {
        return $this->registrationNumber;
    }
    public function setRegistrationNumber(string $registrationNumber): self
    {
        $this->initialized['registrationNumber'] = true;
        $this->registrationNumber = $registrationNumber;
        return $this;
    }
    public function getCompanyName(): string
    {
        return $this->companyName;
    }
    public function setCompanyName(string $companyName): self
    {
        $this->initialized['companyName'] = true;
        $this->companyName = $companyName;
        return $this;
    }
    public function getAmount(): GbCompanyReportExampleResponseReportAdditionalInformationBadDebtDetailsItemAmount
    {
        return $this->amount;
    }
    public function setAmount(GbCompanyReportExampleResponseReportAdditionalInformationBadDebtDetailsItemAmount $amount): self
    {
        $this->initialized['amount'] = true;
        $this->amount = $amount;
        return $this;
    }
}