<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class GbCompanyReportExampleResponseReportAdditionalInformationMortgageDetailsItem extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $mortgageType;
    protected string $dateChargeCreated;
    protected string $dateChargeRegistered;
    protected string $status;
    protected string $personsEntitled;
    protected string $amountSecured;
    protected string $details;
    public function getMortgageType(): string
    {
        return $this->mortgageType;
    }
    public function setMortgageType(string $mortgageType): self
    {
        $this->initialized['mortgageType'] = true;
        $this->mortgageType = $mortgageType;
        return $this;
    }
    public function getDateChargeCreated(): string
    {
        return $this->dateChargeCreated;
    }
    public function setDateChargeCreated(string $dateChargeCreated): self
    {
        $this->initialized['dateChargeCreated'] = true;
        $this->dateChargeCreated = $dateChargeCreated;
        return $this;
    }
    public function getDateChargeRegistered(): string
    {
        return $this->dateChargeRegistered;
    }
    public function setDateChargeRegistered(string $dateChargeRegistered): self
    {
        $this->initialized['dateChargeRegistered'] = true;
        $this->dateChargeRegistered = $dateChargeRegistered;
        return $this;
    }
    public function getStatus(): string
    {
        return $this->status;
    }
    public function setStatus(string $status): self
    {
        $this->initialized['status'] = true;
        $this->status = $status;
        return $this;
    }
    public function getPersonsEntitled(): string
    {
        return $this->personsEntitled;
    }
    public function setPersonsEntitled(string $personsEntitled): self
    {
        $this->initialized['personsEntitled'] = true;
        $this->personsEntitled = $personsEntitled;
        return $this;
    }
    public function getAmountSecured(): string
    {
        return $this->amountSecured;
    }
    public function setAmountSecured(string $amountSecured): self
    {
        $this->initialized['amountSecured'] = true;
        $this->amountSecured = $amountSecured;
        return $this;
    }
    public function getDetails(): string
    {
        return $this->details;
    }
    public function setDetails(string $details): self
    {
        $this->initialized['details'] = true;
        $this->details = $details;
        return $this;
    }
}