<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class GbCompanyReportExampleResponseReportAdditionalInformationCommentariesItem extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected string $commentaryText;
    protected string $positiveNegative;
    public function getCommentaryText(): string
    {
        return $this->commentaryText;
    }
    public function setCommentaryText(string $commentaryText): self
    {
        $this->initialized['commentaryText'] = true;
        $this->commentaryText = $commentaryText;
        return $this;
    }
    public function getPositiveNegative(): string
    {
        return $this->positiveNegative;
    }
    public function setPositiveNegative(string $positiveNegative): self
    {
        $this->initialized['positiveNegative'] = true;
        $this->positiveNegative = $positiveNegative;
        return $this;
    }
}