<?php

/*
 * This file is auto-generated by PHP OpenAPI Generator.
 * DO NOT EDIT MANUALLY — changes will be overwritten when the generator is re-run.
 */
declare (strict_types=1);
namespace LongTermSupport\OpenApiGenerator\Component\OpenApi3\Tests\Expected\Issue337\Model;

/**
 * @extends \ArrayObject<string, mixed>
 */
class ListFreshInvestigationResponse extends \ArrayObject
{
    /**
     * @var array<string, bool>
     */
    protected array $initialized = [];
    public function isInitialized(string $property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected int $totalCount;
    /**
     * @var list<ListFreshInvestigationResponseOrdersItem>
     */
    protected array $orders;
    public function getTotalCount(): int
    {
        return $this->totalCount;
    }
    public function setTotalCount(int $totalCount): self
    {
        $this->initialized['totalCount'] = true;
        $this->totalCount = $totalCount;
        return $this;
    }
    /**
     * @return list<ListFreshInvestigationResponseOrdersItem>
     */
    public function getOrders(): array
    {
        return $this->orders;
    }
    public function setOrders(ListFreshInvestigationResponseOrdersItem ...$orders): self
    {
        $this->initialized['orders'] = true;
        $this->orders = array_values($orders);
        return $this;
    }
}